// Code generated by go-swagger; DO NOT EDIT.

package saved_app_map_search_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// DeleteSavedAppMapSearchGroupReader is a Reader for the DeleteSavedAppMapSearchGroup structure.
type DeleteSavedAppMapSearchGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSavedAppMapSearchGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSavedAppMapSearchGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSavedAppMapSearchGroupOK creates a DeleteSavedAppMapSearchGroupOK with default headers values
func NewDeleteSavedAppMapSearchGroupOK() *DeleteSavedAppMapSearchGroupOK {
	return &DeleteSavedAppMapSearchGroupOK{}
}

/*
DeleteSavedAppMapSearchGroupOK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteSavedAppMapSearchGroupOK struct {
	Payload *models.ResponseContainerSavedAppMapSearchGroup
}

// IsSuccess returns true when this delete saved app map search group o k response has a 2xx status code
func (o *DeleteSavedAppMapSearchGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete saved app map search group o k response has a 3xx status code
func (o *DeleteSavedAppMapSearchGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete saved app map search group o k response has a 4xx status code
func (o *DeleteSavedAppMapSearchGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete saved app map search group o k response has a 5xx status code
func (o *DeleteSavedAppMapSearchGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete saved app map search group o k response a status code equal to that given
func (o *DeleteSavedAppMapSearchGroupOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteSavedAppMapSearchGroupOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/savedappmapsearchgroup/{id}][%d] deleteSavedAppMapSearchGroupOK  %+v", 200, o.Payload)
}

func (o *DeleteSavedAppMapSearchGroupOK) String() string {
	return fmt.Sprintf("[DELETE /api/v2/savedappmapsearchgroup/{id}][%d] deleteSavedAppMapSearchGroupOK  %+v", 200, o.Payload)
}

func (o *DeleteSavedAppMapSearchGroupOK) GetPayload() *models.ResponseContainerSavedAppMapSearchGroup {
	return o.Payload
}

func (o *DeleteSavedAppMapSearchGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerSavedAppMapSearchGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
