// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHideAlertParams creates a new HideAlertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHideAlertParams() *HideAlertParams {
	return &HideAlertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHideAlertParamsWithTimeout creates a new HideAlertParams object
// with the ability to set a timeout on a request.
func NewHideAlertParamsWithTimeout(timeout time.Duration) *HideAlertParams {
	return &HideAlertParams{
		timeout: timeout,
	}
}

// NewHideAlertParamsWithContext creates a new HideAlertParams object
// with the ability to set a context for a request.
func NewHideAlertParamsWithContext(ctx context.Context) *HideAlertParams {
	return &HideAlertParams{
		Context: ctx,
	}
}

// NewHideAlertParamsWithHTTPClient creates a new HideAlertParams object
// with the ability to set a custom HTTPClient for a request.
func NewHideAlertParamsWithHTTPClient(client *http.Client) *HideAlertParams {
	return &HideAlertParams{
		HTTPClient: client,
	}
}

/*
HideAlertParams contains all the parameters to send to the API endpoint

	for the hide alert operation.

	Typically these are written to a http.Request.
*/
type HideAlertParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the hide alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HideAlertParams) WithDefaults() *HideAlertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the hide alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HideAlertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the hide alert params
func (o *HideAlertParams) WithTimeout(timeout time.Duration) *HideAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the hide alert params
func (o *HideAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the hide alert params
func (o *HideAlertParams) WithContext(ctx context.Context) *HideAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the hide alert params
func (o *HideAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the hide alert params
func (o *HideAlertParams) WithHTTPClient(client *http.Client) *HideAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the hide alert params
func (o *HideAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the hide alert params
func (o *HideAlertParams) WithID(id int64) *HideAlertParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the hide alert params
func (o *HideAlertParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *HideAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
