// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetAlertTagsParams creates a new SetAlertTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetAlertTagsParams() *SetAlertTagsParams {
	return &SetAlertTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetAlertTagsParamsWithTimeout creates a new SetAlertTagsParams object
// with the ability to set a timeout on a request.
func NewSetAlertTagsParamsWithTimeout(timeout time.Duration) *SetAlertTagsParams {
	return &SetAlertTagsParams{
		timeout: timeout,
	}
}

// NewSetAlertTagsParamsWithContext creates a new SetAlertTagsParams object
// with the ability to set a context for a request.
func NewSetAlertTagsParamsWithContext(ctx context.Context) *SetAlertTagsParams {
	return &SetAlertTagsParams{
		Context: ctx,
	}
}

// NewSetAlertTagsParamsWithHTTPClient creates a new SetAlertTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetAlertTagsParamsWithHTTPClient(client *http.Client) *SetAlertTagsParams {
	return &SetAlertTagsParams{
		HTTPClient: client,
	}
}

/*
SetAlertTagsParams contains all the parameters to send to the API endpoint

	for the set alert tags operation.

	Typically these are written to a http.Request.
*/
type SetAlertTagsParams struct {

	/* Body.

	     Supported Characters of Tags:
	<pre>Tag names can contain alphanumeric (a-z, A-Z, 0-9),
	dash (-), underscore (_), and colon (:) characters.
	The space character is not supported.</pre>

	*/
	Body []string

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set alert tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAlertTagsParams) WithDefaults() *SetAlertTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set alert tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetAlertTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set alert tags params
func (o *SetAlertTagsParams) WithTimeout(timeout time.Duration) *SetAlertTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set alert tags params
func (o *SetAlertTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set alert tags params
func (o *SetAlertTagsParams) WithContext(ctx context.Context) *SetAlertTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set alert tags params
func (o *SetAlertTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set alert tags params
func (o *SetAlertTagsParams) WithHTTPClient(client *http.Client) *SetAlertTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set alert tags params
func (o *SetAlertTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the set alert tags params
func (o *SetAlertTagsParams) WithBody(body []string) *SetAlertTagsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the set alert tags params
func (o *SetAlertTagsParams) SetBody(body []string) {
	o.Body = body
}

// WithID adds the id to the set alert tags params
func (o *SetAlertTagsParams) WithID(id string) *SetAlertTagsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the set alert tags params
func (o *SetAlertTagsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SetAlertTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
