// Code generated by go-swagger; DO NOT EDIT.

package alert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUnhideAlertParams creates a new UnhideAlertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnhideAlertParams() *UnhideAlertParams {
	return &UnhideAlertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnhideAlertParamsWithTimeout creates a new UnhideAlertParams object
// with the ability to set a timeout on a request.
func NewUnhideAlertParamsWithTimeout(timeout time.Duration) *UnhideAlertParams {
	return &UnhideAlertParams{
		timeout: timeout,
	}
}

// NewUnhideAlertParamsWithContext creates a new UnhideAlertParams object
// with the ability to set a context for a request.
func NewUnhideAlertParamsWithContext(ctx context.Context) *UnhideAlertParams {
	return &UnhideAlertParams{
		Context: ctx,
	}
}

// NewUnhideAlertParamsWithHTTPClient creates a new UnhideAlertParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnhideAlertParamsWithHTTPClient(client *http.Client) *UnhideAlertParams {
	return &UnhideAlertParams{
		HTTPClient: client,
	}
}

/*
UnhideAlertParams contains all the parameters to send to the API endpoint

	for the unhide alert operation.

	Typically these are written to a http.Request.
*/
type UnhideAlertParams struct {

	// ID.
	//
	// Format: int64
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the unhide alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnhideAlertParams) WithDefaults() *UnhideAlertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the unhide alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnhideAlertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the unhide alert params
func (o *UnhideAlertParams) WithTimeout(timeout time.Duration) *UnhideAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unhide alert params
func (o *UnhideAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unhide alert params
func (o *UnhideAlertParams) WithContext(ctx context.Context) *UnhideAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unhide alert params
func (o *UnhideAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unhide alert params
func (o *UnhideAlertParams) WithHTTPClient(client *http.Client) *UnhideAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unhide alert params
func (o *UnhideAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the unhide alert params
func (o *UnhideAlertParams) WithID(id int64) *UnhideAlertParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the unhide alert params
func (o *UnhideAlertParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UnhideAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
