// Code generated by go-swagger; DO NOT EDIT.

package external_link

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetExternalLinkReader is a Reader for the GetExternalLink structure.
type GetExternalLinkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExternalLinkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExternalLinkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExternalLinkOK creates a GetExternalLinkOK with default headers values
func NewGetExternalLinkOK() *GetExternalLinkOK {
	return &GetExternalLinkOK{}
}

/*
GetExternalLinkOK describes a response with status code 200, with default header values.

successful operation
*/
type GetExternalLinkOK struct {
	Payload *models.ResponseContainerExternalLink
}

// IsSuccess returns true when this get external link o k response has a 2xx status code
func (o *GetExternalLinkOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get external link o k response has a 3xx status code
func (o *GetExternalLinkOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get external link o k response has a 4xx status code
func (o *GetExternalLinkOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get external link o k response has a 5xx status code
func (o *GetExternalLinkOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get external link o k response a status code equal to that given
func (o *GetExternalLinkOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetExternalLinkOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/extlink/{id}][%d] getExternalLinkOK  %+v", 200, o.Payload)
}

func (o *GetExternalLinkOK) String() string {
	return fmt.Sprintf("[GET /api/v2/extlink/{id}][%d] getExternalLinkOK  %+v", 200, o.Payload)
}

func (o *GetExternalLinkOK) GetPayload() *models.ResponseContainerExternalLink {
	return o.Payload
}

func (o *GetExternalLinkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerExternalLink)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
