// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchCloudIntegrationDeletedEntitiesParams creates a new SearchCloudIntegrationDeletedEntitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchCloudIntegrationDeletedEntitiesParams() *SearchCloudIntegrationDeletedEntitiesParams {
	return &SearchCloudIntegrationDeletedEntitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchCloudIntegrationDeletedEntitiesParamsWithTimeout creates a new SearchCloudIntegrationDeletedEntitiesParams object
// with the ability to set a timeout on a request.
func NewSearchCloudIntegrationDeletedEntitiesParamsWithTimeout(timeout time.Duration) *SearchCloudIntegrationDeletedEntitiesParams {
	return &SearchCloudIntegrationDeletedEntitiesParams{
		timeout: timeout,
	}
}

// NewSearchCloudIntegrationDeletedEntitiesParamsWithContext creates a new SearchCloudIntegrationDeletedEntitiesParams object
// with the ability to set a context for a request.
func NewSearchCloudIntegrationDeletedEntitiesParamsWithContext(ctx context.Context) *SearchCloudIntegrationDeletedEntitiesParams {
	return &SearchCloudIntegrationDeletedEntitiesParams{
		Context: ctx,
	}
}

// NewSearchCloudIntegrationDeletedEntitiesParamsWithHTTPClient creates a new SearchCloudIntegrationDeletedEntitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchCloudIntegrationDeletedEntitiesParamsWithHTTPClient(client *http.Client) *SearchCloudIntegrationDeletedEntitiesParams {
	return &SearchCloudIntegrationDeletedEntitiesParams{
		HTTPClient: client,
	}
}

/*
SearchCloudIntegrationDeletedEntitiesParams contains all the parameters to send to the API endpoint

	for the search cloud integration deleted entities operation.

	Typically these are written to a http.Request.
*/
type SearchCloudIntegrationDeletedEntitiesParams struct {

	// Body.
	Body *models.SortableSearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search cloud integration deleted entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCloudIntegrationDeletedEntitiesParams) WithDefaults() *SearchCloudIntegrationDeletedEntitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search cloud integration deleted entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCloudIntegrationDeletedEntitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) WithTimeout(timeout time.Duration) *SearchCloudIntegrationDeletedEntitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) WithContext(ctx context.Context) *SearchCloudIntegrationDeletedEntitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) WithHTTPClient(client *http.Client) *SearchCloudIntegrationDeletedEntitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) WithBody(body *models.SortableSearchRequest) *SearchCloudIntegrationDeletedEntitiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search cloud integration deleted entities params
func (o *SearchCloudIntegrationDeletedEntitiesParams) SetBody(body *models.SortableSearchRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchCloudIntegrationDeletedEntitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
