// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchExternalLinkEntitiesParams creates a new SearchExternalLinkEntitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchExternalLinkEntitiesParams() *SearchExternalLinkEntitiesParams {
	return &SearchExternalLinkEntitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchExternalLinkEntitiesParamsWithTimeout creates a new SearchExternalLinkEntitiesParams object
// with the ability to set a timeout on a request.
func NewSearchExternalLinkEntitiesParamsWithTimeout(timeout time.Duration) *SearchExternalLinkEntitiesParams {
	return &SearchExternalLinkEntitiesParams{
		timeout: timeout,
	}
}

// NewSearchExternalLinkEntitiesParamsWithContext creates a new SearchExternalLinkEntitiesParams object
// with the ability to set a context for a request.
func NewSearchExternalLinkEntitiesParamsWithContext(ctx context.Context) *SearchExternalLinkEntitiesParams {
	return &SearchExternalLinkEntitiesParams{
		Context: ctx,
	}
}

// NewSearchExternalLinkEntitiesParamsWithHTTPClient creates a new SearchExternalLinkEntitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchExternalLinkEntitiesParamsWithHTTPClient(client *http.Client) *SearchExternalLinkEntitiesParams {
	return &SearchExternalLinkEntitiesParams{
		HTTPClient: client,
	}
}

/*
SearchExternalLinkEntitiesParams contains all the parameters to send to the API endpoint

	for the search external link entities operation.

	Typically these are written to a http.Request.
*/
type SearchExternalLinkEntitiesParams struct {

	// Body.
	Body *models.SortableSearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search external link entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchExternalLinkEntitiesParams) WithDefaults() *SearchExternalLinkEntitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search external link entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchExternalLinkEntitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) WithTimeout(timeout time.Duration) *SearchExternalLinkEntitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) WithContext(ctx context.Context) *SearchExternalLinkEntitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) WithHTTPClient(client *http.Client) *SearchExternalLinkEntitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) WithBody(body *models.SortableSearchRequest) *SearchExternalLinkEntitiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search external link entities params
func (o *SearchExternalLinkEntitiesParams) SetBody(body *models.SortableSearchRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchExternalLinkEntitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
