// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// SearchSavedTracesEntitiesReader is a Reader for the SearchSavedTracesEntities structure.
type SearchSavedTracesEntitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchSavedTracesEntitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchSavedTracesEntitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchSavedTracesEntitiesOK creates a SearchSavedTracesEntitiesOK with default headers values
func NewSearchSavedTracesEntitiesOK() *SearchSavedTracesEntitiesOK {
	return &SearchSavedTracesEntitiesOK{}
}

/*
SearchSavedTracesEntitiesOK describes a response with status code 200, with default header values.

successful operation
*/
type SearchSavedTracesEntitiesOK struct {
	Payload *models.ResponseContainerPagedSavedTracesSearch
}

// IsSuccess returns true when this search saved traces entities o k response has a 2xx status code
func (o *SearchSavedTracesEntitiesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search saved traces entities o k response has a 3xx status code
func (o *SearchSavedTracesEntitiesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search saved traces entities o k response has a 4xx status code
func (o *SearchSavedTracesEntitiesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search saved traces entities o k response has a 5xx status code
func (o *SearchSavedTracesEntitiesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search saved traces entities o k response a status code equal to that given
func (o *SearchSavedTracesEntitiesOK) IsCode(code int) bool {
	return code == 200
}

func (o *SearchSavedTracesEntitiesOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/search/savedtracessearch][%d] searchSavedTracesEntitiesOK  %+v", 200, o.Payload)
}

func (o *SearchSavedTracesEntitiesOK) String() string {
	return fmt.Sprintf("[POST /api/v2/search/savedtracessearch][%d] searchSavedTracesEntitiesOK  %+v", 200, o.Payload)
}

func (o *SearchSavedTracesEntitiesOK) GetPayload() *models.ResponseContainerPagedSavedTracesSearch {
	return o.Payload
}

func (o *SearchSavedTracesEntitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerPagedSavedTracesSearch)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
