// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchCloudIntegrationDeletedForFacetsParams creates a new SearchCloudIntegrationDeletedForFacetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchCloudIntegrationDeletedForFacetsParams() *SearchCloudIntegrationDeletedForFacetsParams {
	return &SearchCloudIntegrationDeletedForFacetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchCloudIntegrationDeletedForFacetsParamsWithTimeout creates a new SearchCloudIntegrationDeletedForFacetsParams object
// with the ability to set a timeout on a request.
func NewSearchCloudIntegrationDeletedForFacetsParamsWithTimeout(timeout time.Duration) *SearchCloudIntegrationDeletedForFacetsParams {
	return &SearchCloudIntegrationDeletedForFacetsParams{
		timeout: timeout,
	}
}

// NewSearchCloudIntegrationDeletedForFacetsParamsWithContext creates a new SearchCloudIntegrationDeletedForFacetsParams object
// with the ability to set a context for a request.
func NewSearchCloudIntegrationDeletedForFacetsParamsWithContext(ctx context.Context) *SearchCloudIntegrationDeletedForFacetsParams {
	return &SearchCloudIntegrationDeletedForFacetsParams{
		Context: ctx,
	}
}

// NewSearchCloudIntegrationDeletedForFacetsParamsWithHTTPClient creates a new SearchCloudIntegrationDeletedForFacetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchCloudIntegrationDeletedForFacetsParamsWithHTTPClient(client *http.Client) *SearchCloudIntegrationDeletedForFacetsParams {
	return &SearchCloudIntegrationDeletedForFacetsParams{
		HTTPClient: client,
	}
}

/*
SearchCloudIntegrationDeletedForFacetsParams contains all the parameters to send to the API endpoint

	for the search cloud integration deleted for facets operation.

	Typically these are written to a http.Request.
*/
type SearchCloudIntegrationDeletedForFacetsParams struct {

	// Body.
	Body *models.FacetsSearchRequestContainer

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search cloud integration deleted for facets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCloudIntegrationDeletedForFacetsParams) WithDefaults() *SearchCloudIntegrationDeletedForFacetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search cloud integration deleted for facets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchCloudIntegrationDeletedForFacetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) WithTimeout(timeout time.Duration) *SearchCloudIntegrationDeletedForFacetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) WithContext(ctx context.Context) *SearchCloudIntegrationDeletedForFacetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) WithHTTPClient(client *http.Client) *SearchCloudIntegrationDeletedForFacetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) WithBody(body *models.FacetsSearchRequestContainer) *SearchCloudIntegrationDeletedForFacetsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search cloud integration deleted for facets params
func (o *SearchCloudIntegrationDeletedForFacetsParams) SetBody(body *models.FacetsSearchRequestContainer) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchCloudIntegrationDeletedForFacetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
