// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchUserGroupEntitiesParams creates a new SearchUserGroupEntitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchUserGroupEntitiesParams() *SearchUserGroupEntitiesParams {
	return &SearchUserGroupEntitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchUserGroupEntitiesParamsWithTimeout creates a new SearchUserGroupEntitiesParams object
// with the ability to set a timeout on a request.
func NewSearchUserGroupEntitiesParamsWithTimeout(timeout time.Duration) *SearchUserGroupEntitiesParams {
	return &SearchUserGroupEntitiesParams{
		timeout: timeout,
	}
}

// NewSearchUserGroupEntitiesParamsWithContext creates a new SearchUserGroupEntitiesParams object
// with the ability to set a context for a request.
func NewSearchUserGroupEntitiesParamsWithContext(ctx context.Context) *SearchUserGroupEntitiesParams {
	return &SearchUserGroupEntitiesParams{
		Context: ctx,
	}
}

// NewSearchUserGroupEntitiesParamsWithHTTPClient creates a new SearchUserGroupEntitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchUserGroupEntitiesParamsWithHTTPClient(client *http.Client) *SearchUserGroupEntitiesParams {
	return &SearchUserGroupEntitiesParams{
		HTTPClient: client,
	}
}

/*
SearchUserGroupEntitiesParams contains all the parameters to send to the API endpoint

	for the search user group entities operation.

	Typically these are written to a http.Request.
*/
type SearchUserGroupEntitiesParams struct {

	// Body.
	Body *models.SortableSearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search user group entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUserGroupEntitiesParams) WithDefaults() *SearchUserGroupEntitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search user group entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchUserGroupEntitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search user group entities params
func (o *SearchUserGroupEntitiesParams) WithTimeout(timeout time.Duration) *SearchUserGroupEntitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search user group entities params
func (o *SearchUserGroupEntitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search user group entities params
func (o *SearchUserGroupEntitiesParams) WithContext(ctx context.Context) *SearchUserGroupEntitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search user group entities params
func (o *SearchUserGroupEntitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search user group entities params
func (o *SearchUserGroupEntitiesParams) WithHTTPClient(client *http.Client) *SearchUserGroupEntitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search user group entities params
func (o *SearchUserGroupEntitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search user group entities params
func (o *SearchUserGroupEntitiesParams) WithBody(body *models.SortableSearchRequest) *SearchUserGroupEntitiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search user group entities params
func (o *SearchUserGroupEntitiesParams) SetBody(body *models.SortableSearchRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchUserGroupEntitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
