// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchMonitoredApplicationForFacetsParams creates a new SearchMonitoredApplicationForFacetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchMonitoredApplicationForFacetsParams() *SearchMonitoredApplicationForFacetsParams {
	return &SearchMonitoredApplicationForFacetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchMonitoredApplicationForFacetsParamsWithTimeout creates a new SearchMonitoredApplicationForFacetsParams object
// with the ability to set a timeout on a request.
func NewSearchMonitoredApplicationForFacetsParamsWithTimeout(timeout time.Duration) *SearchMonitoredApplicationForFacetsParams {
	return &SearchMonitoredApplicationForFacetsParams{
		timeout: timeout,
	}
}

// NewSearchMonitoredApplicationForFacetsParamsWithContext creates a new SearchMonitoredApplicationForFacetsParams object
// with the ability to set a context for a request.
func NewSearchMonitoredApplicationForFacetsParamsWithContext(ctx context.Context) *SearchMonitoredApplicationForFacetsParams {
	return &SearchMonitoredApplicationForFacetsParams{
		Context: ctx,
	}
}

// NewSearchMonitoredApplicationForFacetsParamsWithHTTPClient creates a new SearchMonitoredApplicationForFacetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchMonitoredApplicationForFacetsParamsWithHTTPClient(client *http.Client) *SearchMonitoredApplicationForFacetsParams {
	return &SearchMonitoredApplicationForFacetsParams{
		HTTPClient: client,
	}
}

/*
SearchMonitoredApplicationForFacetsParams contains all the parameters to send to the API endpoint

	for the search monitored application for facets operation.

	Typically these are written to a http.Request.
*/
type SearchMonitoredApplicationForFacetsParams struct {

	// Body.
	Body *models.FacetsSearchRequestContainer

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search monitored application for facets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMonitoredApplicationForFacetsParams) WithDefaults() *SearchMonitoredApplicationForFacetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search monitored application for facets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchMonitoredApplicationForFacetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) WithTimeout(timeout time.Duration) *SearchMonitoredApplicationForFacetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) WithContext(ctx context.Context) *SearchMonitoredApplicationForFacetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) WithHTTPClient(client *http.Client) *SearchMonitoredApplicationForFacetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) WithBody(body *models.FacetsSearchRequestContainer) *SearchMonitoredApplicationForFacetsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search monitored application for facets params
func (o *SearchMonitoredApplicationForFacetsParams) SetBody(body *models.FacetsSearchRequestContainer) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchMonitoredApplicationForFacetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
