// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchProxyForFacetParams creates a new SearchProxyForFacetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchProxyForFacetParams() *SearchProxyForFacetParams {
	return &SearchProxyForFacetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchProxyForFacetParamsWithTimeout creates a new SearchProxyForFacetParams object
// with the ability to set a timeout on a request.
func NewSearchProxyForFacetParamsWithTimeout(timeout time.Duration) *SearchProxyForFacetParams {
	return &SearchProxyForFacetParams{
		timeout: timeout,
	}
}

// NewSearchProxyForFacetParamsWithContext creates a new SearchProxyForFacetParams object
// with the ability to set a context for a request.
func NewSearchProxyForFacetParamsWithContext(ctx context.Context) *SearchProxyForFacetParams {
	return &SearchProxyForFacetParams{
		Context: ctx,
	}
}

// NewSearchProxyForFacetParamsWithHTTPClient creates a new SearchProxyForFacetParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchProxyForFacetParamsWithHTTPClient(client *http.Client) *SearchProxyForFacetParams {
	return &SearchProxyForFacetParams{
		HTTPClient: client,
	}
}

/*
SearchProxyForFacetParams contains all the parameters to send to the API endpoint

	for the search proxy for facet operation.

	Typically these are written to a http.Request.
*/
type SearchProxyForFacetParams struct {

	// Body.
	Body *models.FacetSearchRequestContainer

	// Facet.
	Facet string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search proxy for facet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchProxyForFacetParams) WithDefaults() *SearchProxyForFacetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search proxy for facet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchProxyForFacetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search proxy for facet params
func (o *SearchProxyForFacetParams) WithTimeout(timeout time.Duration) *SearchProxyForFacetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search proxy for facet params
func (o *SearchProxyForFacetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search proxy for facet params
func (o *SearchProxyForFacetParams) WithContext(ctx context.Context) *SearchProxyForFacetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search proxy for facet params
func (o *SearchProxyForFacetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search proxy for facet params
func (o *SearchProxyForFacetParams) WithHTTPClient(client *http.Client) *SearchProxyForFacetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search proxy for facet params
func (o *SearchProxyForFacetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search proxy for facet params
func (o *SearchProxyForFacetParams) WithBody(body *models.FacetSearchRequestContainer) *SearchProxyForFacetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search proxy for facet params
func (o *SearchProxyForFacetParams) SetBody(body *models.FacetSearchRequestContainer) {
	o.Body = body
}

// WithFacet adds the facet to the search proxy for facet params
func (o *SearchProxyForFacetParams) WithFacet(facet string) *SearchProxyForFacetParams {
	o.SetFacet(facet)
	return o
}

// SetFacet adds the facet to the search proxy for facet params
func (o *SearchProxyForFacetParams) SetFacet(facet string) {
	o.Facet = facet
}

// WriteToRequest writes these params to a swagger request
func (o *SearchProxyForFacetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param facet
	if err := r.SetPathParam("facet", o.Facet); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
