// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// SearchSpanSamplingPolicyDeletedForFacetsReader is a Reader for the SearchSpanSamplingPolicyDeletedForFacets structure.
type SearchSpanSamplingPolicyDeletedForFacetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchSpanSamplingPolicyDeletedForFacetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchSpanSamplingPolicyDeletedForFacetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchSpanSamplingPolicyDeletedForFacetsOK creates a SearchSpanSamplingPolicyDeletedForFacetsOK with default headers values
func NewSearchSpanSamplingPolicyDeletedForFacetsOK() *SearchSpanSamplingPolicyDeletedForFacetsOK {
	return &SearchSpanSamplingPolicyDeletedForFacetsOK{}
}

/*
SearchSpanSamplingPolicyDeletedForFacetsOK describes a response with status code 200, with default header values.

successful operation
*/
type SearchSpanSamplingPolicyDeletedForFacetsOK struct {
	Payload *models.ResponseContainerFacetsResponseContainer
}

// IsSuccess returns true when this search span sampling policy deleted for facets o k response has a 2xx status code
func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this search span sampling policy deleted for facets o k response has a 3xx status code
func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this search span sampling policy deleted for facets o k response has a 4xx status code
func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this search span sampling policy deleted for facets o k response has a 5xx status code
func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this search span sampling policy deleted for facets o k response a status code equal to that given
func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) IsCode(code int) bool {
	return code == 200
}

func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/search/spansamplingpolicy/deleted/facets][%d] searchSpanSamplingPolicyDeletedForFacetsOK  %+v", 200, o.Payload)
}

func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) String() string {
	return fmt.Sprintf("[POST /api/v2/search/spansamplingpolicy/deleted/facets][%d] searchSpanSamplingPolicyDeletedForFacetsOK  %+v", 200, o.Payload)
}

func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) GetPayload() *models.ResponseContainerFacetsResponseContainer {
	return o.Payload
}

func (o *SearchSpanSamplingPolicyDeletedForFacetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerFacetsResponseContainer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
