// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewSearchRegisteredQueryDeletedEntitiesParams creates a new SearchRegisteredQueryDeletedEntitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSearchRegisteredQueryDeletedEntitiesParams() *SearchRegisteredQueryDeletedEntitiesParams {
	return &SearchRegisteredQueryDeletedEntitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSearchRegisteredQueryDeletedEntitiesParamsWithTimeout creates a new SearchRegisteredQueryDeletedEntitiesParams object
// with the ability to set a timeout on a request.
func NewSearchRegisteredQueryDeletedEntitiesParamsWithTimeout(timeout time.Duration) *SearchRegisteredQueryDeletedEntitiesParams {
	return &SearchRegisteredQueryDeletedEntitiesParams{
		timeout: timeout,
	}
}

// NewSearchRegisteredQueryDeletedEntitiesParamsWithContext creates a new SearchRegisteredQueryDeletedEntitiesParams object
// with the ability to set a context for a request.
func NewSearchRegisteredQueryDeletedEntitiesParamsWithContext(ctx context.Context) *SearchRegisteredQueryDeletedEntitiesParams {
	return &SearchRegisteredQueryDeletedEntitiesParams{
		Context: ctx,
	}
}

// NewSearchRegisteredQueryDeletedEntitiesParamsWithHTTPClient creates a new SearchRegisteredQueryDeletedEntitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewSearchRegisteredQueryDeletedEntitiesParamsWithHTTPClient(client *http.Client) *SearchRegisteredQueryDeletedEntitiesParams {
	return &SearchRegisteredQueryDeletedEntitiesParams{
		HTTPClient: client,
	}
}

/*
SearchRegisteredQueryDeletedEntitiesParams contains all the parameters to send to the API endpoint

	for the search registered query deleted entities operation.

	Typically these are written to a http.Request.
*/
type SearchRegisteredQueryDeletedEntitiesParams struct {

	// Body.
	Body *models.SortableSearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the search registered query deleted entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchRegisteredQueryDeletedEntitiesParams) WithDefaults() *SearchRegisteredQueryDeletedEntitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the search registered query deleted entities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SearchRegisteredQueryDeletedEntitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) WithTimeout(timeout time.Duration) *SearchRegisteredQueryDeletedEntitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) WithContext(ctx context.Context) *SearchRegisteredQueryDeletedEntitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) WithHTTPClient(client *http.Client) *SearchRegisteredQueryDeletedEntitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) WithBody(body *models.SortableSearchRequest) *SearchRegisteredQueryDeletedEntitiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the search registered query deleted entities params
func (o *SearchRegisteredQueryDeletedEntitiesParams) SetBody(body *models.SortableSearchRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SearchRegisteredQueryDeletedEntitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
