// Code generated by go-swagger; DO NOT EDIT.

package source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// AddSourceTagReader is a Reader for the AddSourceTag structure.
type AddSourceTagReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddSourceTagReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddSourceTagOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddSourceTagOK creates a AddSourceTagOK with default headers values
func NewAddSourceTagOK() *AddSourceTagOK {
	return &AddSourceTagOK{}
}

/*
AddSourceTagOK describes a response with status code 200, with default header values.

successful operation
*/
type AddSourceTagOK struct {
	Payload *models.ResponseContainer
}

// IsSuccess returns true when this add source tag o k response has a 2xx status code
func (o *AddSourceTagOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add source tag o k response has a 3xx status code
func (o *AddSourceTagOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add source tag o k response has a 4xx status code
func (o *AddSourceTagOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add source tag o k response has a 5xx status code
func (o *AddSourceTagOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add source tag o k response a status code equal to that given
func (o *AddSourceTagOK) IsCode(code int) bool {
	return code == 200
}

func (o *AddSourceTagOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/source/{id}/tag/{tagValue}][%d] addSourceTagOK  %+v", 200, o.Payload)
}

func (o *AddSourceTagOK) String() string {
	return fmt.Sprintf("[PUT /api/v2/source/{id}/tag/{tagValue}][%d] addSourceTagOK  %+v", 200, o.Payload)
}

func (o *AddSourceTagOK) GetPayload() *models.ResponseContainer {
	return o.Payload
}

func (o *AddSourceTagOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
