// Code generated by go-swagger; DO NOT EDIT.

package source

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// DeleteSourceReader is a Reader for the DeleteSource structure.
type DeleteSourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteSourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSourceOK creates a DeleteSourceOK with default headers values
func NewDeleteSourceOK() *DeleteSourceOK {
	return &DeleteSourceOK{}
}

/*
DeleteSourceOK describes a response with status code 200, with default header values.

successful operation
*/
type DeleteSourceOK struct {
	Payload *models.ResponseContainerSource
}

// IsSuccess returns true when this delete source o k response has a 2xx status code
func (o *DeleteSourceOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete source o k response has a 3xx status code
func (o *DeleteSourceOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete source o k response has a 4xx status code
func (o *DeleteSourceOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete source o k response has a 5xx status code
func (o *DeleteSourceOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete source o k response a status code equal to that given
func (o *DeleteSourceOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeleteSourceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/source/{id}][%d] deleteSourceOK  %+v", 200, o.Payload)
}

func (o *DeleteSourceOK) String() string {
	return fmt.Sprintf("[DELETE /api/v2/source/{id}][%d] deleteSourceOK  %+v", 200, o.Payload)
}

func (o *DeleteSourceOK) GetPayload() *models.ResponseContainerSource {
	return o.Payload
}

func (o *DeleteSourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerSource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
