// Code generated by go-swagger; DO NOT EDIT.

package recent_traces_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewCreateRecentTracesSearchParams creates a new CreateRecentTracesSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRecentTracesSearchParams() *CreateRecentTracesSearchParams {
	return &CreateRecentTracesSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRecentTracesSearchParamsWithTimeout creates a new CreateRecentTracesSearchParams object
// with the ability to set a timeout on a request.
func NewCreateRecentTracesSearchParamsWithTimeout(timeout time.Duration) *CreateRecentTracesSearchParams {
	return &CreateRecentTracesSearchParams{
		timeout: timeout,
	}
}

// NewCreateRecentTracesSearchParamsWithContext creates a new CreateRecentTracesSearchParams object
// with the ability to set a context for a request.
func NewCreateRecentTracesSearchParamsWithContext(ctx context.Context) *CreateRecentTracesSearchParams {
	return &CreateRecentTracesSearchParams{
		Context: ctx,
	}
}

// NewCreateRecentTracesSearchParamsWithHTTPClient creates a new CreateRecentTracesSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRecentTracesSearchParamsWithHTTPClient(client *http.Client) *CreateRecentTracesSearchParams {
	return &CreateRecentTracesSearchParams{
		HTTPClient: client,
	}
}

/*
CreateRecentTracesSearchParams contains all the parameters to send to the API endpoint

	for the create recent traces search operation.

	Typically these are written to a http.Request.
*/
type CreateRecentTracesSearchParams struct {

	/* Body.

	     Example Body:
	<pre>{
	  "searchFilters": {
	    "filters": [
	      {
	        "filterType": "OPERATION",
	        "values": {
	          "logicalValue": [
	            [
	              "beachshirts.", "shopping.", "'*"
	            ]
	          ]
	        }
	      }
	    ]
	  }
	}</pre>
	*/
	Body *models.RecentTracesSearch

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create recent traces search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRecentTracesSearchParams) WithDefaults() *CreateRecentTracesSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create recent traces search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRecentTracesSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create recent traces search params
func (o *CreateRecentTracesSearchParams) WithTimeout(timeout time.Duration) *CreateRecentTracesSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create recent traces search params
func (o *CreateRecentTracesSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create recent traces search params
func (o *CreateRecentTracesSearchParams) WithContext(ctx context.Context) *CreateRecentTracesSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create recent traces search params
func (o *CreateRecentTracesSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create recent traces search params
func (o *CreateRecentTracesSearchParams) WithHTTPClient(client *http.Client) *CreateRecentTracesSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create recent traces search params
func (o *CreateRecentTracesSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create recent traces search params
func (o *CreateRecentTracesSearchParams) WithBody(body *models.RecentTracesSearch) *CreateRecentTracesSearchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create recent traces search params
func (o *CreateRecentTracesSearchParams) SetBody(body *models.RecentTracesSearch) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRecentTracesSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
