// Code generated by go-swagger; DO NOT EDIT.

package saved_traces_search_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// AddSavedTracesSearchToGroupReader is a Reader for the AddSavedTracesSearchToGroup structure.
type AddSavedTracesSearchToGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddSavedTracesSearchToGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddSavedTracesSearchToGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddSavedTracesSearchToGroupOK creates a AddSavedTracesSearchToGroupOK with default headers values
func NewAddSavedTracesSearchToGroupOK() *AddSavedTracesSearchToGroupOK {
	return &AddSavedTracesSearchToGroupOK{}
}

/*
AddSavedTracesSearchToGroupOK describes a response with status code 200, with default header values.

successful operation
*/
type AddSavedTracesSearchToGroupOK struct {
	Payload *models.ResponseContainer
}

// IsSuccess returns true when this add saved traces search to group o k response has a 2xx status code
func (o *AddSavedTracesSearchToGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add saved traces search to group o k response has a 3xx status code
func (o *AddSavedTracesSearchToGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add saved traces search to group o k response has a 4xx status code
func (o *AddSavedTracesSearchToGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add saved traces search to group o k response has a 5xx status code
func (o *AddSavedTracesSearchToGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add saved traces search to group o k response a status code equal to that given
func (o *AddSavedTracesSearchToGroupOK) IsCode(code int) bool {
	return code == 200
}

func (o *AddSavedTracesSearchToGroupOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/savedtracessearchgroup/{id}/addSearch/{searchId}][%d] addSavedTracesSearchToGroupOK  %+v", 200, o.Payload)
}

func (o *AddSavedTracesSearchToGroupOK) String() string {
	return fmt.Sprintf("[POST /api/v2/savedtracessearchgroup/{id}/addSearch/{searchId}][%d] addSavedTracesSearchToGroupOK  %+v", 200, o.Payload)
}

func (o *AddSavedTracesSearchToGroupOK) GetPayload() *models.ResponseContainer {
	return o.Payload
}

func (o *AddSavedTracesSearchToGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
