// Code generated by go-swagger; DO NOT EDIT.

package saved_traces_search_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddSavedTracesSearchToGroupParams creates a new AddSavedTracesSearchToGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddSavedTracesSearchToGroupParams() *AddSavedTracesSearchToGroupParams {
	return &AddSavedTracesSearchToGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddSavedTracesSearchToGroupParamsWithTimeout creates a new AddSavedTracesSearchToGroupParams object
// with the ability to set a timeout on a request.
func NewAddSavedTracesSearchToGroupParamsWithTimeout(timeout time.Duration) *AddSavedTracesSearchToGroupParams {
	return &AddSavedTracesSearchToGroupParams{
		timeout: timeout,
	}
}

// NewAddSavedTracesSearchToGroupParamsWithContext creates a new AddSavedTracesSearchToGroupParams object
// with the ability to set a context for a request.
func NewAddSavedTracesSearchToGroupParamsWithContext(ctx context.Context) *AddSavedTracesSearchToGroupParams {
	return &AddSavedTracesSearchToGroupParams{
		Context: ctx,
	}
}

// NewAddSavedTracesSearchToGroupParamsWithHTTPClient creates a new AddSavedTracesSearchToGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddSavedTracesSearchToGroupParamsWithHTTPClient(client *http.Client) *AddSavedTracesSearchToGroupParams {
	return &AddSavedTracesSearchToGroupParams{
		HTTPClient: client,
	}
}

/*
AddSavedTracesSearchToGroupParams contains all the parameters to send to the API endpoint

	for the add saved traces search to group operation.

	Typically these are written to a http.Request.
*/
type AddSavedTracesSearchToGroupParams struct {

	// ID.
	ID string

	// SearchID.
	SearchID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add saved traces search to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSavedTracesSearchToGroupParams) WithDefaults() *AddSavedTracesSearchToGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add saved traces search to group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddSavedTracesSearchToGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) WithTimeout(timeout time.Duration) *AddSavedTracesSearchToGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) WithContext(ctx context.Context) *AddSavedTracesSearchToGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) WithHTTPClient(client *http.Client) *AddSavedTracesSearchToGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) WithID(id string) *AddSavedTracesSearchToGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) SetID(id string) {
	o.ID = id
}

// WithSearchID adds the searchID to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) WithSearchID(searchID string) *AddSavedTracesSearchToGroupParams {
	o.SetSearchID(searchID)
	return o
}

// SetSearchID adds the searchId to the add saved traces search to group params
func (o *AddSavedTracesSearchToGroupParams) SetSearchID(searchID string) {
	o.SearchID = searchID
}

// WriteToRequest writes these params to a swagger request
func (o *AddSavedTracesSearchToGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param searchId
	if err := r.SetPathParam("searchId", o.SearchID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
