// Code generated by go-swagger; DO NOT EDIT.

package saved_traces_search_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// UpdateSavedTracesSearchGroupReader is a Reader for the UpdateSavedTracesSearchGroup structure.
type UpdateSavedTracesSearchGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSavedTracesSearchGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateSavedTracesSearchGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateSavedTracesSearchGroupOK creates a UpdateSavedTracesSearchGroupOK with default headers values
func NewUpdateSavedTracesSearchGroupOK() *UpdateSavedTracesSearchGroupOK {
	return &UpdateSavedTracesSearchGroupOK{}
}

/*
UpdateSavedTracesSearchGroupOK describes a response with status code 200, with default header values.

successful operation
*/
type UpdateSavedTracesSearchGroupOK struct {
	Payload *models.ResponseContainerSavedTracesSearchGroup
}

// IsSuccess returns true when this update saved traces search group o k response has a 2xx status code
func (o *UpdateSavedTracesSearchGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update saved traces search group o k response has a 3xx status code
func (o *UpdateSavedTracesSearchGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update saved traces search group o k response has a 4xx status code
func (o *UpdateSavedTracesSearchGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update saved traces search group o k response has a 5xx status code
func (o *UpdateSavedTracesSearchGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update saved traces search group o k response a status code equal to that given
func (o *UpdateSavedTracesSearchGroupOK) IsCode(code int) bool {
	return code == 200
}

func (o *UpdateSavedTracesSearchGroupOK) Error() string {
	return fmt.Sprintf("[PUT /api/v2/savedtracessearchgroup/{id}][%d] updateSavedTracesSearchGroupOK  %+v", 200, o.Payload)
}

func (o *UpdateSavedTracesSearchGroupOK) String() string {
	return fmt.Sprintf("[PUT /api/v2/savedtracessearchgroup/{id}][%d] updateSavedTracesSearchGroupOK  %+v", 200, o.Payload)
}

func (o *UpdateSavedTracesSearchGroupOK) GetPayload() *models.ResponseContainerSavedTracesSearchGroup {
	return o.Payload
}

func (o *UpdateSavedTracesSearchGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerSavedTracesSearchGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
