// Code generated by go-swagger; DO NOT EDIT.

package notificant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// TestNotificantReader is a Reader for the TestNotificant structure.
type TestNotificantReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TestNotificantReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTestNotificantOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTestNotificantOK creates a TestNotificantOK with default headers values
func NewTestNotificantOK() *TestNotificantOK {
	return &TestNotificantOK{}
}

/*
TestNotificantOK describes a response with status code 200, with default header values.

successful operation
*/
type TestNotificantOK struct {
	Payload *models.ResponseContainerNotificant
}

// IsSuccess returns true when this test notificant o k response has a 2xx status code
func (o *TestNotificantOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this test notificant o k response has a 3xx status code
func (o *TestNotificantOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this test notificant o k response has a 4xx status code
func (o *TestNotificantOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this test notificant o k response has a 5xx status code
func (o *TestNotificantOK) IsServerError() bool {
	return false
}

// IsCode returns true when this test notificant o k response a status code equal to that given
func (o *TestNotificantOK) IsCode(code int) bool {
	return code == 200
}

func (o *TestNotificantOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/notificant/test/{id}][%d] testNotificantOK  %+v", 200, o.Payload)
}

func (o *TestNotificantOK) String() string {
	return fmt.Sprintf("[POST /api/v2/notificant/test/{id}][%d] testNotificantOK  %+v", 200, o.Payload)
}

func (o *TestNotificantOK) GetPayload() *models.ResponseContainerNotificant {
	return o.Payload
}

func (o *TestNotificantOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerNotificant)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
