// Code generated by go-swagger; DO NOT EDIT.

package span_sampling_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetSpanSamplingPolicyVersionReader is a Reader for the GetSpanSamplingPolicyVersion structure.
type GetSpanSamplingPolicyVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSpanSamplingPolicyVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSpanSamplingPolicyVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSpanSamplingPolicyVersionOK creates a GetSpanSamplingPolicyVersionOK with default headers values
func NewGetSpanSamplingPolicyVersionOK() *GetSpanSamplingPolicyVersionOK {
	return &GetSpanSamplingPolicyVersionOK{}
}

/*
GetSpanSamplingPolicyVersionOK describes a response with status code 200, with default header values.

successful operation
*/
type GetSpanSamplingPolicyVersionOK struct {
	Payload *models.ResponseContainerSpanSamplingPolicy
}

// IsSuccess returns true when this get span sampling policy version o k response has a 2xx status code
func (o *GetSpanSamplingPolicyVersionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get span sampling policy version o k response has a 3xx status code
func (o *GetSpanSamplingPolicyVersionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get span sampling policy version o k response has a 4xx status code
func (o *GetSpanSamplingPolicyVersionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get span sampling policy version o k response has a 5xx status code
func (o *GetSpanSamplingPolicyVersionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get span sampling policy version o k response a status code equal to that given
func (o *GetSpanSamplingPolicyVersionOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetSpanSamplingPolicyVersionOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/spansamplingpolicy/{id}/history/{version}][%d] getSpanSamplingPolicyVersionOK  %+v", 200, o.Payload)
}

func (o *GetSpanSamplingPolicyVersionOK) String() string {
	return fmt.Sprintf("[GET /api/v2/spansamplingpolicy/{id}/history/{version}][%d] getSpanSamplingPolicyVersionOK  %+v", 200, o.Payload)
}

func (o *GetSpanSamplingPolicyVersionOK) GetPayload() *models.ResponseContainerSpanSamplingPolicy {
	return o.Payload
}

func (o *GetSpanSamplingPolicyVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerSpanSamplingPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
