// Code generated by go-swagger; DO NOT EDIT.

package span_sampling_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetSpanSamplingPolicyReader is a Reader for the GetSpanSamplingPolicy structure.
type GetSpanSamplingPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSpanSamplingPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSpanSamplingPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSpanSamplingPolicyOK creates a GetSpanSamplingPolicyOK with default headers values
func NewGetSpanSamplingPolicyOK() *GetSpanSamplingPolicyOK {
	return &GetSpanSamplingPolicyOK{}
}

/*
GetSpanSamplingPolicyOK describes a response with status code 200, with default header values.

successful operation
*/
type GetSpanSamplingPolicyOK struct {
	Payload *models.ResponseContainerSpanSamplingPolicy
}

// IsSuccess returns true when this get span sampling policy o k response has a 2xx status code
func (o *GetSpanSamplingPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get span sampling policy o k response has a 3xx status code
func (o *GetSpanSamplingPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get span sampling policy o k response has a 4xx status code
func (o *GetSpanSamplingPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get span sampling policy o k response has a 5xx status code
func (o *GetSpanSamplingPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get span sampling policy o k response a status code equal to that given
func (o *GetSpanSamplingPolicyOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetSpanSamplingPolicyOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/spansamplingpolicy/{id}][%d] getSpanSamplingPolicyOK  %+v", 200, o.Payload)
}

func (o *GetSpanSamplingPolicyOK) String() string {
	return fmt.Sprintf("[GET /api/v2/spansamplingpolicy/{id}][%d] getSpanSamplingPolicyOK  %+v", 200, o.Payload)
}

func (o *GetSpanSamplingPolicyOK) GetPayload() *models.ResponseContainerSpanSamplingPolicy {
	return o.Payload
}

func (o *GetSpanSamplingPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerSpanSamplingPolicy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
