// Code generated by go-swagger; DO NOT EDIT.

package span_sampling_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUndeleteSpanSamplingPolicyParams creates a new UndeleteSpanSamplingPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUndeleteSpanSamplingPolicyParams() *UndeleteSpanSamplingPolicyParams {
	return &UndeleteSpanSamplingPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUndeleteSpanSamplingPolicyParamsWithTimeout creates a new UndeleteSpanSamplingPolicyParams object
// with the ability to set a timeout on a request.
func NewUndeleteSpanSamplingPolicyParamsWithTimeout(timeout time.Duration) *UndeleteSpanSamplingPolicyParams {
	return &UndeleteSpanSamplingPolicyParams{
		timeout: timeout,
	}
}

// NewUndeleteSpanSamplingPolicyParamsWithContext creates a new UndeleteSpanSamplingPolicyParams object
// with the ability to set a context for a request.
func NewUndeleteSpanSamplingPolicyParamsWithContext(ctx context.Context) *UndeleteSpanSamplingPolicyParams {
	return &UndeleteSpanSamplingPolicyParams{
		Context: ctx,
	}
}

// NewUndeleteSpanSamplingPolicyParamsWithHTTPClient creates a new UndeleteSpanSamplingPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewUndeleteSpanSamplingPolicyParamsWithHTTPClient(client *http.Client) *UndeleteSpanSamplingPolicyParams {
	return &UndeleteSpanSamplingPolicyParams{
		HTTPClient: client,
	}
}

/*
UndeleteSpanSamplingPolicyParams contains all the parameters to send to the API endpoint

	for the undelete span sampling policy operation.

	Typically these are written to a http.Request.
*/
type UndeleteSpanSamplingPolicyParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the undelete span sampling policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UndeleteSpanSamplingPolicyParams) WithDefaults() *UndeleteSpanSamplingPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the undelete span sampling policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UndeleteSpanSamplingPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) WithTimeout(timeout time.Duration) *UndeleteSpanSamplingPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) WithContext(ctx context.Context) *UndeleteSpanSamplingPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) WithHTTPClient(client *http.Client) *UndeleteSpanSamplingPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) WithID(id string) *UndeleteSpanSamplingPolicyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the undelete span sampling policy params
func (o *UndeleteSpanSamplingPolicyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UndeleteSpanSamplingPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
