// Code generated by go-swagger; DO NOT EDIT.

package saved_traces_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDefaultAppMapSearch2Params creates a new DefaultAppMapSearch2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDefaultAppMapSearch2Params() *DefaultAppMapSearch2Params {
	return &DefaultAppMapSearch2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewDefaultAppMapSearch2ParamsWithTimeout creates a new DefaultAppMapSearch2Params object
// with the ability to set a timeout on a request.
func NewDefaultAppMapSearch2ParamsWithTimeout(timeout time.Duration) *DefaultAppMapSearch2Params {
	return &DefaultAppMapSearch2Params{
		timeout: timeout,
	}
}

// NewDefaultAppMapSearch2ParamsWithContext creates a new DefaultAppMapSearch2Params object
// with the ability to set a context for a request.
func NewDefaultAppMapSearch2ParamsWithContext(ctx context.Context) *DefaultAppMapSearch2Params {
	return &DefaultAppMapSearch2Params{
		Context: ctx,
	}
}

// NewDefaultAppMapSearch2ParamsWithHTTPClient creates a new DefaultAppMapSearch2Params object
// with the ability to set a custom HTTPClient for a request.
func NewDefaultAppMapSearch2ParamsWithHTTPClient(client *http.Client) *DefaultAppMapSearch2Params {
	return &DefaultAppMapSearch2Params{
		HTTPClient: client,
	}
}

/*
DefaultAppMapSearch2Params contains all the parameters to send to the API endpoint

	for the default app map search 2 operation.

	Typically these are written to a http.Request.
*/
type DefaultAppMapSearch2Params struct {

	// DefaultTracesSearch.
	DefaultTracesSearch *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the default app map search 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DefaultAppMapSearch2Params) WithDefaults() *DefaultAppMapSearch2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the default app map search 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DefaultAppMapSearch2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) WithTimeout(timeout time.Duration) *DefaultAppMapSearch2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) WithContext(ctx context.Context) *DefaultAppMapSearch2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) WithHTTPClient(client *http.Client) *DefaultAppMapSearch2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDefaultTracesSearch adds the defaultTracesSearch to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) WithDefaultTracesSearch(defaultTracesSearch *string) *DefaultAppMapSearch2Params {
	o.SetDefaultTracesSearch(defaultTracesSearch)
	return o
}

// SetDefaultTracesSearch adds the defaultTracesSearch to the default app map search 2 params
func (o *DefaultAppMapSearch2Params) SetDefaultTracesSearch(defaultTracesSearch *string) {
	o.DefaultTracesSearch = defaultTracesSearch
}

// WriteToRequest writes these params to a swagger request
func (o *DefaultAppMapSearch2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DefaultTracesSearch != nil {

		// query param defaultTracesSearch
		var qrDefaultTracesSearch string

		if o.DefaultTracesSearch != nil {
			qrDefaultTracesSearch = *o.DefaultTracesSearch
		}
		qDefaultTracesSearch := qrDefaultTracesSearch
		if qDefaultTracesSearch != "" {

			if err := r.SetQueryParam("defaultTracesSearch", qDefaultTracesSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
