// Code generated by go-swagger; DO NOT EDIT.

package saved_traces_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAllSavedTracesSearchesForUserReader is a Reader for the GetAllSavedTracesSearchesForUser structure.
type GetAllSavedTracesSearchesForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllSavedTracesSearchesForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllSavedTracesSearchesForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllSavedTracesSearchesForUserOK creates a GetAllSavedTracesSearchesForUserOK with default headers values
func NewGetAllSavedTracesSearchesForUserOK() *GetAllSavedTracesSearchesForUserOK {
	return &GetAllSavedTracesSearchesForUserOK{}
}

/*
GetAllSavedTracesSearchesForUserOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllSavedTracesSearchesForUserOK struct {
	Payload *models.ResponseContainerPagedSavedTracesSearch
}

// IsSuccess returns true when this get all saved traces searches for user o k response has a 2xx status code
func (o *GetAllSavedTracesSearchesForUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all saved traces searches for user o k response has a 3xx status code
func (o *GetAllSavedTracesSearchesForUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all saved traces searches for user o k response has a 4xx status code
func (o *GetAllSavedTracesSearchesForUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all saved traces searches for user o k response has a 5xx status code
func (o *GetAllSavedTracesSearchesForUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all saved traces searches for user o k response a status code equal to that given
func (o *GetAllSavedTracesSearchesForUserOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAllSavedTracesSearchesForUserOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/savedtracessearch/owned][%d] getAllSavedTracesSearchesForUserOK  %+v", 200, o.Payload)
}

func (o *GetAllSavedTracesSearchesForUserOK) String() string {
	return fmt.Sprintf("[GET /api/v2/savedtracessearch/owned][%d] getAllSavedTracesSearchesForUserOK  %+v", 200, o.Payload)
}

func (o *GetAllSavedTracesSearchesForUserOK) GetPayload() *models.ResponseContainerPagedSavedTracesSearch {
	return o.Payload
}

func (o *GetAllSavedTracesSearchesForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerPagedSavedTracesSearch)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
