// Code generated by go-swagger; DO NOT EDIT.

package event

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAllEventsWithTimeRangeReader is a Reader for the GetAllEventsWithTimeRange structure.
type GetAllEventsWithTimeRangeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllEventsWithTimeRangeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllEventsWithTimeRangeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllEventsWithTimeRangeOK creates a GetAllEventsWithTimeRangeOK with default headers values
func NewGetAllEventsWithTimeRangeOK() *GetAllEventsWithTimeRangeOK {
	return &GetAllEventsWithTimeRangeOK{}
}

/*
GetAllEventsWithTimeRangeOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllEventsWithTimeRangeOK struct {
	Payload *models.ResponseContainerPagedEvent
}

// IsSuccess returns true when this get all events with time range o k response has a 2xx status code
func (o *GetAllEventsWithTimeRangeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all events with time range o k response has a 3xx status code
func (o *GetAllEventsWithTimeRangeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all events with time range o k response has a 4xx status code
func (o *GetAllEventsWithTimeRangeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all events with time range o k response has a 5xx status code
func (o *GetAllEventsWithTimeRangeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all events with time range o k response a status code equal to that given
func (o *GetAllEventsWithTimeRangeOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAllEventsWithTimeRangeOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/event][%d] getAllEventsWithTimeRangeOK  %+v", 200, o.Payload)
}

func (o *GetAllEventsWithTimeRangeOK) String() string {
	return fmt.Sprintf("[GET /api/v2/event][%d] getAllEventsWithTimeRangeOK  %+v", 200, o.Payload)
}

func (o *GetAllEventsWithTimeRangeOK) GetPayload() *models.ResponseContainerPagedEvent {
	return o.Payload
}

func (o *GetAllEventsWithTimeRangeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerPagedEvent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
