// Code generated by go-swagger; DO NOT EDIT.

package user_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// AddUsersToUserGroupReader is a Reader for the AddUsersToUserGroup structure.
type AddUsersToUserGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddUsersToUserGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddUsersToUserGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddUsersToUserGroupOK creates a AddUsersToUserGroupOK with default headers values
func NewAddUsersToUserGroupOK() *AddUsersToUserGroupOK {
	return &AddUsersToUserGroupOK{}
}

/*
AddUsersToUserGroupOK describes a response with status code 200, with default header values.

successful operation
*/
type AddUsersToUserGroupOK struct {
	Payload *models.ResponseContainerUserGroupModel
}

// IsSuccess returns true when this add users to user group o k response has a 2xx status code
func (o *AddUsersToUserGroupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add users to user group o k response has a 3xx status code
func (o *AddUsersToUserGroupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add users to user group o k response has a 4xx status code
func (o *AddUsersToUserGroupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add users to user group o k response has a 5xx status code
func (o *AddUsersToUserGroupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add users to user group o k response a status code equal to that given
func (o *AddUsersToUserGroupOK) IsCode(code int) bool {
	return code == 200
}

func (o *AddUsersToUserGroupOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/usergroup/{id}/addUsers][%d] addUsersToUserGroupOK  %+v", 200, o.Payload)
}

func (o *AddUsersToUserGroupOK) String() string {
	return fmt.Sprintf("[POST /api/v2/usergroup/{id}/addUsers][%d] addUsersToUserGroupOK  %+v", 200, o.Payload)
}

func (o *AddUsersToUserGroupOK) GetPayload() *models.ResponseContainerUserGroupModel {
	return o.Payload
}

func (o *AddUsersToUserGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerUserGroupModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
