// Code generated by go-swagger; DO NOT EDIT.

package user_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewCreateUserGroupParams creates a new CreateUserGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateUserGroupParams() *CreateUserGroupParams {
	return &CreateUserGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateUserGroupParamsWithTimeout creates a new CreateUserGroupParams object
// with the ability to set a timeout on a request.
func NewCreateUserGroupParamsWithTimeout(timeout time.Duration) *CreateUserGroupParams {
	return &CreateUserGroupParams{
		timeout: timeout,
	}
}

// NewCreateUserGroupParamsWithContext creates a new CreateUserGroupParams object
// with the ability to set a context for a request.
func NewCreateUserGroupParamsWithContext(ctx context.Context) *CreateUserGroupParams {
	return &CreateUserGroupParams{
		Context: ctx,
	}
}

// NewCreateUserGroupParamsWithHTTPClient creates a new CreateUserGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateUserGroupParamsWithHTTPClient(client *http.Client) *CreateUserGroupParams {
	return &CreateUserGroupParams{
		HTTPClient: client,
	}
}

/*
CreateUserGroupParams contains all the parameters to send to the API endpoint

	for the create user group operation.

	Typically these are written to a http.Request.
*/
type CreateUserGroupParams struct {

	/* Body.

	     Example Body:
	<pre>{
	  "name": "UserGroup name",
	  "roleIDs": [
	  "role1",
	  "role2",
	  "role3"
	  ],
	  "description": "UserGroup description"
	}</pre>
	*/
	Body *models.UserGroupWrite

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserGroupParams) WithDefaults() *CreateUserGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateUserGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create user group params
func (o *CreateUserGroupParams) WithTimeout(timeout time.Duration) *CreateUserGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create user group params
func (o *CreateUserGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create user group params
func (o *CreateUserGroupParams) WithContext(ctx context.Context) *CreateUserGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create user group params
func (o *CreateUserGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create user group params
func (o *CreateUserGroupParams) WithHTTPClient(client *http.Client) *CreateUserGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create user group params
func (o *CreateUserGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create user group params
func (o *CreateUserGroupParams) WithBody(body *models.UserGroupWrite) *CreateUserGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create user group params
func (o *CreateUserGroupParams) SetBody(body *models.UserGroupWrite) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateUserGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
