// Code generated by go-swagger; DO NOT EDIT.

package user_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAllUserGroupsParams creates a new GetAllUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllUserGroupsParams() *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllUserGroupsParamsWithTimeout creates a new GetAllUserGroupsParams object
// with the ability to set a timeout on a request.
func NewGetAllUserGroupsParamsWithTimeout(timeout time.Duration) *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		timeout: timeout,
	}
}

// NewGetAllUserGroupsParamsWithContext creates a new GetAllUserGroupsParams object
// with the ability to set a context for a request.
func NewGetAllUserGroupsParamsWithContext(ctx context.Context) *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		Context: ctx,
	}
}

// NewGetAllUserGroupsParamsWithHTTPClient creates a new GetAllUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllUserGroupsParamsWithHTTPClient(client *http.Client) *GetAllUserGroupsParams {
	return &GetAllUserGroupsParams{
		HTTPClient: client,
	}
}

/*
GetAllUserGroupsParams contains all the parameters to send to the API endpoint

	for the get all user groups operation.

	Typically these are written to a http.Request.
*/
type GetAllUserGroupsParams struct {

	// Limit.
	//
	// Format: int32
	// Default: 100
	Limit *int32

	// Offset.
	//
	// Format: int32
	Offset *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllUserGroupsParams) WithDefaults() *GetAllUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllUserGroupsParams) SetDefaults() {
	var (
		limitDefault = int32(100)

		offsetDefault = int32(0)
	)

	val := GetAllUserGroupsParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get all user groups params
func (o *GetAllUserGroupsParams) WithTimeout(timeout time.Duration) *GetAllUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all user groups params
func (o *GetAllUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all user groups params
func (o *GetAllUserGroupsParams) WithContext(ctx context.Context) *GetAllUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all user groups params
func (o *GetAllUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all user groups params
func (o *GetAllUserGroupsParams) WithHTTPClient(client *http.Client) *GetAllUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all user groups params
func (o *GetAllUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get all user groups params
func (o *GetAllUserGroupsParams) WithLimit(limit *int32) *GetAllUserGroupsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get all user groups params
func (o *GetAllUserGroupsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get all user groups params
func (o *GetAllUserGroupsParams) WithOffset(offset *int32) *GetAllUserGroupsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get all user groups params
func (o *GetAllUserGroupsParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
