// Code generated by go-swagger; DO NOT EDIT.

package user_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveRolesFromUserGroupParams creates a new RemoveRolesFromUserGroupParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveRolesFromUserGroupParams() *RemoveRolesFromUserGroupParams {
	return &RemoveRolesFromUserGroupParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveRolesFromUserGroupParamsWithTimeout creates a new RemoveRolesFromUserGroupParams object
// with the ability to set a timeout on a request.
func NewRemoveRolesFromUserGroupParamsWithTimeout(timeout time.Duration) *RemoveRolesFromUserGroupParams {
	return &RemoveRolesFromUserGroupParams{
		timeout: timeout,
	}
}

// NewRemoveRolesFromUserGroupParamsWithContext creates a new RemoveRolesFromUserGroupParams object
// with the ability to set a context for a request.
func NewRemoveRolesFromUserGroupParamsWithContext(ctx context.Context) *RemoveRolesFromUserGroupParams {
	return &RemoveRolesFromUserGroupParams{
		Context: ctx,
	}
}

// NewRemoveRolesFromUserGroupParamsWithHTTPClient creates a new RemoveRolesFromUserGroupParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveRolesFromUserGroupParamsWithHTTPClient(client *http.Client) *RemoveRolesFromUserGroupParams {
	return &RemoveRolesFromUserGroupParams{
		HTTPClient: client,
	}
}

/*
RemoveRolesFromUserGroupParams contains all the parameters to send to the API endpoint

	for the remove roles from user group operation.

	Typically these are written to a http.Request.
*/
type RemoveRolesFromUserGroupParams struct {

	/* Body.

	   List of roles that should be removed from user group
	*/
	Body []string

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove roles from user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveRolesFromUserGroupParams) WithDefaults() *RemoveRolesFromUserGroupParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove roles from user group params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveRolesFromUserGroupParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) WithTimeout(timeout time.Duration) *RemoveRolesFromUserGroupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) WithContext(ctx context.Context) *RemoveRolesFromUserGroupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) WithHTTPClient(client *http.Client) *RemoveRolesFromUserGroupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) WithBody(body []string) *RemoveRolesFromUserGroupParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) SetBody(body []string) {
	o.Body = body
}

// WithID adds the id to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) WithID(id string) *RemoveRolesFromUserGroupParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the remove roles from user group params
func (o *RemoveRolesFromUserGroupParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveRolesFromUserGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
