// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// QueryAPIReader is a Reader for the QueryAPI structure.
type QueryAPIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryAPIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryAPIOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewQueryAPIOK creates a QueryAPIOK with default headers values
func NewQueryAPIOK() *QueryAPIOK {
	return &QueryAPIOK{}
}

/*
QueryAPIOK describes a response with status code 200, with default header values.

successful operation
*/
type QueryAPIOK struct {
	Payload *models.QueryResult
}

// IsSuccess returns true when this query Api o k response has a 2xx status code
func (o *QueryAPIOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query Api o k response has a 3xx status code
func (o *QueryAPIOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query Api o k response has a 4xx status code
func (o *QueryAPIOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query Api o k response has a 5xx status code
func (o *QueryAPIOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query Api o k response a status code equal to that given
func (o *QueryAPIOK) IsCode(code int) bool {
	return code == 200
}

func (o *QueryAPIOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/chart/api][%d] queryApiOK  %+v", 200, o.Payload)
}

func (o *QueryAPIOK) String() string {
	return fmt.Sprintf("[GET /api/v2/chart/api][%d] queryApiOK  %+v", 200, o.Payload)
}

func (o *QueryAPIOK) GetPayload() *models.QueryResult {
	return o.Payload
}

func (o *QueryAPIOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QueryResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
