// Code generated by go-swagger; DO NOT EDIT.

package cloud_integration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAWSExternalIDReader is a Reader for the GetAWSExternalID structure.
type GetAWSExternalIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAWSExternalIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAWSExternalIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAWSExternalIDOK creates a GetAWSExternalIDOK with default headers values
func NewGetAWSExternalIDOK() *GetAWSExternalIDOK {
	return &GetAWSExternalIDOK{}
}

/*
GetAWSExternalIDOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAWSExternalIDOK struct {
	Payload *models.ResponseContainerString
}

// IsSuccess returns true when this get a w s external Id o k response has a 2xx status code
func (o *GetAWSExternalIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get a w s external Id o k response has a 3xx status code
func (o *GetAWSExternalIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get a w s external Id o k response has a 4xx status code
func (o *GetAWSExternalIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get a w s external Id o k response has a 5xx status code
func (o *GetAWSExternalIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get a w s external Id o k response a status code equal to that given
func (o *GetAWSExternalIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAWSExternalIDOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/cloudintegration/awsExternalId/{id}][%d] getAWSExternalIdOK  %+v", 200, o.Payload)
}

func (o *GetAWSExternalIDOK) String() string {
	return fmt.Sprintf("[GET /api/v2/cloudintegration/awsExternalId/{id}][%d] getAWSExternalIdOK  %+v", 200, o.Payload)
}

func (o *GetAWSExternalIDOK) GetPayload() *models.ResponseContainerString {
	return o.Payload
}

func (o *GetAWSExternalIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerString)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
