// Code generated by go-swagger; DO NOT EDIT.

package integration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllIntegrationInManifestsMinParams creates a new GetAllIntegrationInManifestsMinParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllIntegrationInManifestsMinParams() *GetAllIntegrationInManifestsMinParams {
	return &GetAllIntegrationInManifestsMinParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllIntegrationInManifestsMinParamsWithTimeout creates a new GetAllIntegrationInManifestsMinParams object
// with the ability to set a timeout on a request.
func NewGetAllIntegrationInManifestsMinParamsWithTimeout(timeout time.Duration) *GetAllIntegrationInManifestsMinParams {
	return &GetAllIntegrationInManifestsMinParams{
		timeout: timeout,
	}
}

// NewGetAllIntegrationInManifestsMinParamsWithContext creates a new GetAllIntegrationInManifestsMinParams object
// with the ability to set a context for a request.
func NewGetAllIntegrationInManifestsMinParamsWithContext(ctx context.Context) *GetAllIntegrationInManifestsMinParams {
	return &GetAllIntegrationInManifestsMinParams{
		Context: ctx,
	}
}

// NewGetAllIntegrationInManifestsMinParamsWithHTTPClient creates a new GetAllIntegrationInManifestsMinParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllIntegrationInManifestsMinParamsWithHTTPClient(client *http.Client) *GetAllIntegrationInManifestsMinParams {
	return &GetAllIntegrationInManifestsMinParams{
		HTTPClient: client,
	}
}

/*
GetAllIntegrationInManifestsMinParams contains all the parameters to send to the API endpoint

	for the get all integration in manifests min operation.

	Typically these are written to a http.Request.
*/
type GetAllIntegrationInManifestsMinParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all integration in manifests min params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllIntegrationInManifestsMinParams) WithDefaults() *GetAllIntegrationInManifestsMinParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all integration in manifests min params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllIntegrationInManifestsMinParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all integration in manifests min params
func (o *GetAllIntegrationInManifestsMinParams) WithTimeout(timeout time.Duration) *GetAllIntegrationInManifestsMinParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all integration in manifests min params
func (o *GetAllIntegrationInManifestsMinParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all integration in manifests min params
func (o *GetAllIntegrationInManifestsMinParams) WithContext(ctx context.Context) *GetAllIntegrationInManifestsMinParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all integration in manifests min params
func (o *GetAllIntegrationInManifestsMinParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all integration in manifests min params
func (o *GetAllIntegrationInManifestsMinParams) WithHTTPClient(client *http.Client) *GetAllIntegrationInManifestsMinParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all integration in manifests min params
func (o *GetAllIntegrationInManifestsMinParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllIntegrationInManifestsMinParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
