// Code generated by go-swagger; DO NOT EDIT.

package integration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUninstallAllIntegrationAlertsParams creates a new UninstallAllIntegrationAlertsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUninstallAllIntegrationAlertsParams() *UninstallAllIntegrationAlertsParams {
	return &UninstallAllIntegrationAlertsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUninstallAllIntegrationAlertsParamsWithTimeout creates a new UninstallAllIntegrationAlertsParams object
// with the ability to set a timeout on a request.
func NewUninstallAllIntegrationAlertsParamsWithTimeout(timeout time.Duration) *UninstallAllIntegrationAlertsParams {
	return &UninstallAllIntegrationAlertsParams{
		timeout: timeout,
	}
}

// NewUninstallAllIntegrationAlertsParamsWithContext creates a new UninstallAllIntegrationAlertsParams object
// with the ability to set a context for a request.
func NewUninstallAllIntegrationAlertsParamsWithContext(ctx context.Context) *UninstallAllIntegrationAlertsParams {
	return &UninstallAllIntegrationAlertsParams{
		Context: ctx,
	}
}

// NewUninstallAllIntegrationAlertsParamsWithHTTPClient creates a new UninstallAllIntegrationAlertsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUninstallAllIntegrationAlertsParamsWithHTTPClient(client *http.Client) *UninstallAllIntegrationAlertsParams {
	return &UninstallAllIntegrationAlertsParams{
		HTTPClient: client,
	}
}

/*
UninstallAllIntegrationAlertsParams contains all the parameters to send to the API endpoint

	for the uninstall all integration alerts operation.

	Typically these are written to a http.Request.
*/
type UninstallAllIntegrationAlertsParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the uninstall all integration alerts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UninstallAllIntegrationAlertsParams) WithDefaults() *UninstallAllIntegrationAlertsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the uninstall all integration alerts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UninstallAllIntegrationAlertsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) WithTimeout(timeout time.Duration) *UninstallAllIntegrationAlertsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) WithContext(ctx context.Context) *UninstallAllIntegrationAlertsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) WithHTTPClient(client *http.Client) *UninstallAllIntegrationAlertsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) WithID(id string) *UninstallAllIntegrationAlertsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the uninstall all integration alerts params
func (o *UninstallAllIntegrationAlertsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UninstallAllIntegrationAlertsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
