// Code generated by go-swagger; DO NOT EDIT.

package integration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUninstallIntegrationParams creates a new UninstallIntegrationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUninstallIntegrationParams() *UninstallIntegrationParams {
	return &UninstallIntegrationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUninstallIntegrationParamsWithTimeout creates a new UninstallIntegrationParams object
// with the ability to set a timeout on a request.
func NewUninstallIntegrationParamsWithTimeout(timeout time.Duration) *UninstallIntegrationParams {
	return &UninstallIntegrationParams{
		timeout: timeout,
	}
}

// NewUninstallIntegrationParamsWithContext creates a new UninstallIntegrationParams object
// with the ability to set a context for a request.
func NewUninstallIntegrationParamsWithContext(ctx context.Context) *UninstallIntegrationParams {
	return &UninstallIntegrationParams{
		Context: ctx,
	}
}

// NewUninstallIntegrationParamsWithHTTPClient creates a new UninstallIntegrationParams object
// with the ability to set a custom HTTPClient for a request.
func NewUninstallIntegrationParamsWithHTTPClient(client *http.Client) *UninstallIntegrationParams {
	return &UninstallIntegrationParams{
		HTTPClient: client,
	}
}

/*
UninstallIntegrationParams contains all the parameters to send to the API endpoint

	for the uninstall integration operation.

	Typically these are written to a http.Request.
*/
type UninstallIntegrationParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the uninstall integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UninstallIntegrationParams) WithDefaults() *UninstallIntegrationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the uninstall integration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UninstallIntegrationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the uninstall integration params
func (o *UninstallIntegrationParams) WithTimeout(timeout time.Duration) *UninstallIntegrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the uninstall integration params
func (o *UninstallIntegrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the uninstall integration params
func (o *UninstallIntegrationParams) WithContext(ctx context.Context) *UninstallIntegrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the uninstall integration params
func (o *UninstallIntegrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the uninstall integration params
func (o *UninstallIntegrationParams) WithHTTPClient(client *http.Client) *UninstallIntegrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the uninstall integration params
func (o *UninstallIntegrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the uninstall integration params
func (o *UninstallIntegrationParams) WithID(id string) *UninstallIntegrationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the uninstall integration params
func (o *UninstallIntegrationParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UninstallIntegrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
