// Code generated by go-swagger; DO NOT EDIT.

package saved_app_map_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetSavedAppMapSearchReader is a Reader for the GetSavedAppMapSearch structure.
type GetSavedAppMapSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSavedAppMapSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSavedAppMapSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSavedAppMapSearchOK creates a GetSavedAppMapSearchOK with default headers values
func NewGetSavedAppMapSearchOK() *GetSavedAppMapSearchOK {
	return &GetSavedAppMapSearchOK{}
}

/*
GetSavedAppMapSearchOK describes a response with status code 200, with default header values.

successful operation
*/
type GetSavedAppMapSearchOK struct {
	Payload *models.ResponseContainerSavedAppMapSearch
}

// IsSuccess returns true when this get saved app map search o k response has a 2xx status code
func (o *GetSavedAppMapSearchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get saved app map search o k response has a 3xx status code
func (o *GetSavedAppMapSearchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get saved app map search o k response has a 4xx status code
func (o *GetSavedAppMapSearchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get saved app map search o k response has a 5xx status code
func (o *GetSavedAppMapSearchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get saved app map search o k response a status code equal to that given
func (o *GetSavedAppMapSearchOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetSavedAppMapSearchOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/savedappmapsearch/{id}][%d] getSavedAppMapSearchOK  %+v", 200, o.Payload)
}

func (o *GetSavedAppMapSearchOK) String() string {
	return fmt.Sprintf("[GET /api/v2/savedappmapsearch/{id}][%d] getSavedAppMapSearchOK  %+v", 200, o.Payload)
}

func (o *GetSavedAppMapSearchOK) GetPayload() *models.ResponseContainerSavedAppMapSearch {
	return o.Payload
}

func (o *GetSavedAppMapSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerSavedAppMapSearch)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
