// Code generated by go-swagger; DO NOT EDIT.

package saved_app_map_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewUpdateSavedAppMapSearchForUserParams creates a new UpdateSavedAppMapSearchForUserParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateSavedAppMapSearchForUserParams() *UpdateSavedAppMapSearchForUserParams {
	return &UpdateSavedAppMapSearchForUserParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSavedAppMapSearchForUserParamsWithTimeout creates a new UpdateSavedAppMapSearchForUserParams object
// with the ability to set a timeout on a request.
func NewUpdateSavedAppMapSearchForUserParamsWithTimeout(timeout time.Duration) *UpdateSavedAppMapSearchForUserParams {
	return &UpdateSavedAppMapSearchForUserParams{
		timeout: timeout,
	}
}

// NewUpdateSavedAppMapSearchForUserParamsWithContext creates a new UpdateSavedAppMapSearchForUserParams object
// with the ability to set a context for a request.
func NewUpdateSavedAppMapSearchForUserParamsWithContext(ctx context.Context) *UpdateSavedAppMapSearchForUserParams {
	return &UpdateSavedAppMapSearchForUserParams{
		Context: ctx,
	}
}

// NewUpdateSavedAppMapSearchForUserParamsWithHTTPClient creates a new UpdateSavedAppMapSearchForUserParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateSavedAppMapSearchForUserParamsWithHTTPClient(client *http.Client) *UpdateSavedAppMapSearchForUserParams {
	return &UpdateSavedAppMapSearchForUserParams{
		HTTPClient: client,
	}
}

/*
UpdateSavedAppMapSearchForUserParams contains all the parameters to send to the API endpoint

	for the update saved app map search for user operation.

	Typically these are written to a http.Request.
*/
type UpdateSavedAppMapSearchForUserParams struct {

	/* Body.

	     Example Body:
	<pre>{
	  "name": "beachshirts shopping",
	  "searchFilters": {
	    "filters": [
	      {
	        "filterType": "OPERATION",
	        "values": {
	          "logicalValue": [
	            [
	              "beachshirts.", "shopping"
	            ]
	          ]
	        }
	      }
	    ]
	  }
	}</pre>
	*/
	Body *models.SavedAppMapSearch

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update saved app map search for user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSavedAppMapSearchForUserParams) WithDefaults() *UpdateSavedAppMapSearchForUserParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update saved app map search for user params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateSavedAppMapSearchForUserParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) WithTimeout(timeout time.Duration) *UpdateSavedAppMapSearchForUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) WithContext(ctx context.Context) *UpdateSavedAppMapSearchForUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) WithHTTPClient(client *http.Client) *UpdateSavedAppMapSearchForUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) WithBody(body *models.SavedAppMapSearch) *UpdateSavedAppMapSearchForUserParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) SetBody(body *models.SavedAppMapSearch) {
	o.Body = body
}

// WithID adds the id to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) WithID(id string) *UpdateSavedAppMapSearchForUserParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update saved app map search for user params
func (o *UpdateSavedAppMapSearchForUserParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSavedAppMapSearchForUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
