// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetDashboardAccessControlListParams creates a new GetDashboardAccessControlListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDashboardAccessControlListParams() *GetDashboardAccessControlListParams {
	return &GetDashboardAccessControlListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDashboardAccessControlListParamsWithTimeout creates a new GetDashboardAccessControlListParams object
// with the ability to set a timeout on a request.
func NewGetDashboardAccessControlListParamsWithTimeout(timeout time.Duration) *GetDashboardAccessControlListParams {
	return &GetDashboardAccessControlListParams{
		timeout: timeout,
	}
}

// NewGetDashboardAccessControlListParamsWithContext creates a new GetDashboardAccessControlListParams object
// with the ability to set a context for a request.
func NewGetDashboardAccessControlListParamsWithContext(ctx context.Context) *GetDashboardAccessControlListParams {
	return &GetDashboardAccessControlListParams{
		Context: ctx,
	}
}

// NewGetDashboardAccessControlListParamsWithHTTPClient creates a new GetDashboardAccessControlListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDashboardAccessControlListParamsWithHTTPClient(client *http.Client) *GetDashboardAccessControlListParams {
	return &GetDashboardAccessControlListParams{
		HTTPClient: client,
	}
}

/*
GetDashboardAccessControlListParams contains all the parameters to send to the API endpoint

	for the get dashboard access control list operation.

	Typically these are written to a http.Request.
*/
type GetDashboardAccessControlListParams struct {

	// ID.
	ID []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dashboard access control list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDashboardAccessControlListParams) WithDefaults() *GetDashboardAccessControlListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dashboard access control list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDashboardAccessControlListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) WithTimeout(timeout time.Duration) *GetDashboardAccessControlListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) WithContext(ctx context.Context) *GetDashboardAccessControlListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) WithHTTPClient(client *http.Client) *GetDashboardAccessControlListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) WithID(id []string) *GetDashboardAccessControlListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get dashboard access control list params
func (o *GetDashboardAccessControlListParams) SetID(id []string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDashboardAccessControlListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// binding items for id
		joinedID := o.bindParamID(reg)

		// query array param id
		if err := r.SetQueryParam("id", joinedID...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetDashboardAccessControlList binds the parameter id
func (o *GetDashboardAccessControlListParams) bindParamID(formats strfmt.Registry) []string {
	iDIR := o.ID

	var iDIC []string
	for _, iDIIR := range iDIR { // explode []string

		iDIIV := iDIIR // string as string
		iDIC = append(iDIC, iDIIV)
	}

	// items.CollectionFormat: "multi"
	iDIS := swag.JoinByFormat(iDIC, "multi")

	return iDIS
}
