// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewRemoveDashboardAccessParams creates a new RemoveDashboardAccessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveDashboardAccessParams() *RemoveDashboardAccessParams {
	return &RemoveDashboardAccessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveDashboardAccessParamsWithTimeout creates a new RemoveDashboardAccessParams object
// with the ability to set a timeout on a request.
func NewRemoveDashboardAccessParamsWithTimeout(timeout time.Duration) *RemoveDashboardAccessParams {
	return &RemoveDashboardAccessParams{
		timeout: timeout,
	}
}

// NewRemoveDashboardAccessParamsWithContext creates a new RemoveDashboardAccessParams object
// with the ability to set a context for a request.
func NewRemoveDashboardAccessParamsWithContext(ctx context.Context) *RemoveDashboardAccessParams {
	return &RemoveDashboardAccessParams{
		Context: ctx,
	}
}

// NewRemoveDashboardAccessParamsWithHTTPClient creates a new RemoveDashboardAccessParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveDashboardAccessParamsWithHTTPClient(client *http.Client) *RemoveDashboardAccessParams {
	return &RemoveDashboardAccessParams{
		HTTPClient: client,
	}
}

/*
RemoveDashboardAccessParams contains all the parameters to send to the API endpoint

	for the remove dashboard access operation.

	Typically these are written to a http.Request.
*/
type RemoveDashboardAccessParams struct {

	// Body.
	Body []*models.AccessControlListWriteDTO

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove dashboard access params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveDashboardAccessParams) WithDefaults() *RemoveDashboardAccessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove dashboard access params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveDashboardAccessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove dashboard access params
func (o *RemoveDashboardAccessParams) WithTimeout(timeout time.Duration) *RemoveDashboardAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove dashboard access params
func (o *RemoveDashboardAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove dashboard access params
func (o *RemoveDashboardAccessParams) WithContext(ctx context.Context) *RemoveDashboardAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove dashboard access params
func (o *RemoveDashboardAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove dashboard access params
func (o *RemoveDashboardAccessParams) WithHTTPClient(client *http.Client) *RemoveDashboardAccessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove dashboard access params
func (o *RemoveDashboardAccessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove dashboard access params
func (o *RemoveDashboardAccessParams) WithBody(body []*models.AccessControlListWriteDTO) *RemoveDashboardAccessParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove dashboard access params
func (o *RemoveDashboardAccessParams) SetBody(body []*models.AccessControlListWriteDTO) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveDashboardAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
