// Code generated by go-swagger; DO NOT EDIT.

package account_user_and_service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// AddIngestionPolicyReader is a Reader for the AddIngestionPolicy structure.
type AddIngestionPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddIngestionPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddIngestionPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddIngestionPolicyOK creates a AddIngestionPolicyOK with default headers values
func NewAddIngestionPolicyOK() *AddIngestionPolicyOK {
	return &AddIngestionPolicyOK{}
}

/*
AddIngestionPolicyOK describes a response with status code 200, with default header values.

successful operation
*/
type AddIngestionPolicyOK struct {
	Payload *models.ResponseContainer
}

// IsSuccess returns true when this add ingestion policy o k response has a 2xx status code
func (o *AddIngestionPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add ingestion policy o k response has a 3xx status code
func (o *AddIngestionPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add ingestion policy o k response has a 4xx status code
func (o *AddIngestionPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add ingestion policy o k response has a 5xx status code
func (o *AddIngestionPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add ingestion policy o k response a status code equal to that given
func (o *AddIngestionPolicyOK) IsCode(code int) bool {
	return code == 200
}

func (o *AddIngestionPolicyOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/account/addingestionpolicy][%d] addIngestionPolicyOK  %+v", 200, o.Payload)
}

func (o *AddIngestionPolicyOK) String() string {
	return fmt.Sprintf("[POST /api/v2/account/addingestionpolicy][%d] addIngestionPolicyOK  %+v", 200, o.Payload)
}

func (o *AddIngestionPolicyOK) GetPayload() *models.ResponseContainer {
	return o.Payload
}

func (o *AddIngestionPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
