// Code generated by go-swagger; DO NOT EDIT.

package account_user_and_service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveAccountFromUserGroupsParams creates a new RemoveAccountFromUserGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveAccountFromUserGroupsParams() *RemoveAccountFromUserGroupsParams {
	return &RemoveAccountFromUserGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveAccountFromUserGroupsParamsWithTimeout creates a new RemoveAccountFromUserGroupsParams object
// with the ability to set a timeout on a request.
func NewRemoveAccountFromUserGroupsParamsWithTimeout(timeout time.Duration) *RemoveAccountFromUserGroupsParams {
	return &RemoveAccountFromUserGroupsParams{
		timeout: timeout,
	}
}

// NewRemoveAccountFromUserGroupsParamsWithContext creates a new RemoveAccountFromUserGroupsParams object
// with the ability to set a context for a request.
func NewRemoveAccountFromUserGroupsParamsWithContext(ctx context.Context) *RemoveAccountFromUserGroupsParams {
	return &RemoveAccountFromUserGroupsParams{
		Context: ctx,
	}
}

// NewRemoveAccountFromUserGroupsParamsWithHTTPClient creates a new RemoveAccountFromUserGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveAccountFromUserGroupsParamsWithHTTPClient(client *http.Client) *RemoveAccountFromUserGroupsParams {
	return &RemoveAccountFromUserGroupsParams{
		HTTPClient: client,
	}
}

/*
RemoveAccountFromUserGroupsParams contains all the parameters to send to the API endpoint

	for the remove account from user groups operation.

	Typically these are written to a http.Request.
*/
type RemoveAccountFromUserGroupsParams struct {

	/* Body.

	   The list of groups that should be removed from the account
	*/
	Body []string

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove account from user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveAccountFromUserGroupsParams) WithDefaults() *RemoveAccountFromUserGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove account from user groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveAccountFromUserGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) WithTimeout(timeout time.Duration) *RemoveAccountFromUserGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) WithContext(ctx context.Context) *RemoveAccountFromUserGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) WithHTTPClient(client *http.Client) *RemoveAccountFromUserGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) WithBody(body []string) *RemoveAccountFromUserGroupsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) SetBody(body []string) {
	o.Body = body
}

// WithID adds the id to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) WithID(id string) *RemoveAccountFromUserGroupsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the remove account from user groups params
func (o *RemoveAccountFromUserGroupsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveAccountFromUserGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
