// Code generated by go-swagger; DO NOT EDIT.

package account_user_and_service_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// RemoveIngestionPoliciesReader is a Reader for the RemoveIngestionPolicies structure.
type RemoveIngestionPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveIngestionPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoveIngestionPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoveIngestionPoliciesOK creates a RemoveIngestionPoliciesOK with default headers values
func NewRemoveIngestionPoliciesOK() *RemoveIngestionPoliciesOK {
	return &RemoveIngestionPoliciesOK{}
}

/*
RemoveIngestionPoliciesOK describes a response with status code 200, with default header values.

successful operation
*/
type RemoveIngestionPoliciesOK struct {
	Payload *models.ResponseContainer
}

// IsSuccess returns true when this remove ingestion policies o k response has a 2xx status code
func (o *RemoveIngestionPoliciesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this remove ingestion policies o k response has a 3xx status code
func (o *RemoveIngestionPoliciesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this remove ingestion policies o k response has a 4xx status code
func (o *RemoveIngestionPoliciesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this remove ingestion policies o k response has a 5xx status code
func (o *RemoveIngestionPoliciesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this remove ingestion policies o k response a status code equal to that given
func (o *RemoveIngestionPoliciesOK) IsCode(code int) bool {
	return code == 200
}

func (o *RemoveIngestionPoliciesOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/account/removeingestionpolicies][%d] removeIngestionPoliciesOK  %+v", 200, o.Payload)
}

func (o *RemoveIngestionPoliciesOK) String() string {
	return fmt.Sprintf("[POST /api/v2/account/removeingestionpolicies][%d] removeIngestionPoliciesOK  %+v", 200, o.Payload)
}

func (o *RemoveIngestionPoliciesOK) GetPayload() *models.ResponseContainer {
	return o.Payload
}

func (o *RemoveIngestionPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
