// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FacetsResponseContainer facets response container
//
// swagger:model FacetsResponseContainer
type FacetsResponseContainer struct {

	// The requested facets, returned in a map whose key is the facet property and whose value is a list of facet values
	Facets map[string][]string `json:"facets,omitempty"`

	// The requested limit
	Limit int64 `json:"limit,omitempty"`
}

// Validate validates this facets response container
func (m *FacetsResponseContainer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this facets response container based on context it is used
func (m *FacetsResponseContainer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FacetsResponseContainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FacetsResponseContainer) UnmarshalBinary(b []byte) error {
	var res FacetsResponseContainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
