// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IngestionPolicyMetadata Api model for ingestion policy metadata
//
// swagger:model IngestionPolicyMetadata
type IngestionPolicyMetadata struct {

	// ID of the customer to which the ingestion policy metadata belongs
	Customer string `json:"customer,omitempty"`

	// The unique ID for the ingestion policy to which the metadata belongs
	IngestionPolicyID string `json:"ingestionPolicyId,omitempty"`

	// ingestion policy usage in billing period
	UsageInBillingPeriod int32 `json:"usageInBillingPeriod,omitempty"`
}

// Validate validates this ingestion policy metadata
func (m *IngestionPolicyMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ingestion policy metadata based on context it is used
func (m *IngestionPolicyMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IngestionPolicyMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IngestionPolicyMetadata) UnmarshalBinary(b []byte) error {
	var res IngestionPolicyMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
