// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsPolicyReadModel Metrics policy entity for read requests.
//
// swagger:model MetricsPolicyReadModel
type MetricsPolicyReadModel struct {

	// The customer identifier of the metrics policy
	Customer string `json:"customer,omitempty"`

	// The list of policy rules of the metrics policy
	PolicyRules []*PolicyRuleReadModel `json:"policyRules"`

	// The date time of the metrics policy update
	UpdatedEpochMillis int64 `json:"updatedEpochMillis,omitempty"`

	// The id of the metrics policy updater
	UpdaterID string `json:"updaterId,omitempty"`
}

// Validate validates this metrics policy read model
func (m *MetricsPolicyReadModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePolicyRules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricsPolicyReadModel) validatePolicyRules(formats strfmt.Registry) error {
	if swag.IsZero(m.PolicyRules) { // not required
		return nil
	}

	for i := 0; i < len(m.PolicyRules); i++ {
		if swag.IsZero(m.PolicyRules[i]) { // not required
			continue
		}

		if m.PolicyRules[i] != nil {
			if err := m.PolicyRules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("policyRules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("policyRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this metrics policy read model based on the context it is used
func (m *MetricsPolicyReadModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePolicyRules(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricsPolicyReadModel) contextValidatePolicyRules(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PolicyRules); i++ {

		if m.PolicyRules[i] != nil {
			if err := m.PolicyRules[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("policyRules" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("policyRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetricsPolicyReadModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsPolicyReadModel) UnmarshalBinary(b []byte) error {
	var res MetricsPolicyReadModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
