// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RolePropertiesDTO role properties d t o
//
// swagger:model RolePropertiesDTO
type RolePropertiesDTO struct {

	// deletable
	Deletable bool `json:"deletable,omitempty"`

	// name editable
	NameEditable bool `json:"nameEditable,omitempty"`

	// perms editable
	PermsEditable bool `json:"permsEditable,omitempty"`

	// users addable
	UsersAddable bool `json:"usersAddable,omitempty"`

	// users removable
	UsersRemovable bool `json:"usersRemovable,omitempty"`
}

// Validate validates this role properties d t o
func (m *RolePropertiesDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this role properties d t o based on context it is used
func (m *RolePropertiesDTO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RolePropertiesDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RolePropertiesDTO) UnmarshalBinary(b []byte) error {
	var res RolePropertiesDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
