// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Span span
//
// swagger:model Span
type Span struct {

	// Annotations (key-value pairs) of this span
	Annotations []map[string]string `json:"annotations"`

	// Span duration (in milliseconds)
	DurationMs int64 `json:"durationMs,omitempty"`

	// Source/Host of this span
	Host string `json:"host,omitempty"`

	// Span name
	Name string `json:"name,omitempty"`

	// Span ID
	SpanID string `json:"spanId,omitempty"`

	// Span start time (in milliseconds)
	StartMs int64 `json:"startMs,omitempty"`

	// Trace ID
	TraceID string `json:"traceId,omitempty"`
}

// Validate validates this span
func (m *Span) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this span based on context it is used
func (m *Span) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Span) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Span) UnmarshalBinary(b []byte) error {
	var res Span
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
