// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Trace trace
//
// swagger:model Trace
type Trace struct {

	// Trace end time (in milliseconds)
	EndMs int64 `json:"end_ms,omitempty"`

	// Spans associated with this trace
	Spans []*Span `json:"spans"`

	// Trace start time (in milliseconds)
	StartMs int64 `json:"start_ms,omitempty"`

	// Trace total duration (in milliseconds)
	TotalDurationMs int64 `json:"total_duration_ms,omitempty"`

	// Trace ID
	TraceID string `json:"traceId,omitempty"`
}

// Validate validates this trace
func (m *Trace) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpans(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Trace) validateSpans(formats strfmt.Registry) error {
	if swag.IsZero(m.Spans) { // not required
		return nil
	}

	for i := 0; i < len(m.Spans); i++ {
		if swag.IsZero(m.Spans[i]) { // not required
			continue
		}

		if m.Spans[i] != nil {
			if err := m.Spans[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spans" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spans" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this trace based on the context it is used
func (m *Trace) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSpans(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Trace) contextValidateSpans(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Spans); i++ {

		if m.Spans[i] != nil {
			if err := m.Spans[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spans" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spans" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Trace) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Trace) UnmarshalBinary(b []byte) error {
	var res Trace
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
