// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Tuple List of string elements.
//
// swagger:model Tuple
type Tuple struct {

	// elements
	Elements []string `json:"elements"`
}

// Validate validates this tuple
func (m *Tuple) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tuple based on context it is used
func (m *Tuple) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tuple) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tuple) UnmarshalBinary(b []byte) error {
	var res Tuple
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
