// Code generated by go-swagger; DO NOT EDIT.

package api_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewGenerateTokenServiceAccountParams creates a new GenerateTokenServiceAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGenerateTokenServiceAccountParams() *GenerateTokenServiceAccountParams {
	return &GenerateTokenServiceAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGenerateTokenServiceAccountParamsWithTimeout creates a new GenerateTokenServiceAccountParams object
// with the ability to set a timeout on a request.
func NewGenerateTokenServiceAccountParamsWithTimeout(timeout time.Duration) *GenerateTokenServiceAccountParams {
	return &GenerateTokenServiceAccountParams{
		timeout: timeout,
	}
}

// NewGenerateTokenServiceAccountParamsWithContext creates a new GenerateTokenServiceAccountParams object
// with the ability to set a context for a request.
func NewGenerateTokenServiceAccountParamsWithContext(ctx context.Context) *GenerateTokenServiceAccountParams {
	return &GenerateTokenServiceAccountParams{
		Context: ctx,
	}
}

// NewGenerateTokenServiceAccountParamsWithHTTPClient creates a new GenerateTokenServiceAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewGenerateTokenServiceAccountParamsWithHTTPClient(client *http.Client) *GenerateTokenServiceAccountParams {
	return &GenerateTokenServiceAccountParams{
		HTTPClient: client,
	}
}

/*
GenerateTokenServiceAccountParams contains all the parameters to send to the API endpoint

	for the generate token service account operation.

	Typically these are written to a http.Request.
*/
type GenerateTokenServiceAccountParams struct {

	// Body.
	Body *models.UserAPIToken

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the generate token service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateTokenServiceAccountParams) WithDefaults() *GenerateTokenServiceAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the generate token service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GenerateTokenServiceAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the generate token service account params
func (o *GenerateTokenServiceAccountParams) WithTimeout(timeout time.Duration) *GenerateTokenServiceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the generate token service account params
func (o *GenerateTokenServiceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the generate token service account params
func (o *GenerateTokenServiceAccountParams) WithContext(ctx context.Context) *GenerateTokenServiceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the generate token service account params
func (o *GenerateTokenServiceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the generate token service account params
func (o *GenerateTokenServiceAccountParams) WithHTTPClient(client *http.Client) *GenerateTokenServiceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the generate token service account params
func (o *GenerateTokenServiceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the generate token service account params
func (o *GenerateTokenServiceAccountParams) WithBody(body *models.UserAPIToken) *GenerateTokenServiceAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the generate token service account params
func (o *GenerateTokenServiceAccountParams) SetBody(body *models.UserAPIToken) {
	o.Body = body
}

// WithID adds the id to the generate token service account params
func (o *GenerateTokenServiceAccountParams) WithID(id string) *GenerateTokenServiceAccountParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the generate token service account params
func (o *GenerateTokenServiceAccountParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GenerateTokenServiceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
