// Code generated by go-swagger; DO NOT EDIT.

package api_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetCustomerTokenReader is a Reader for the GetCustomerToken structure.
type GetCustomerTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomerTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomerTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCustomerTokenOK creates a GetCustomerTokenOK with default headers values
func NewGetCustomerTokenOK() *GetCustomerTokenOK {
	return &GetCustomerTokenOK{}
}

/*
GetCustomerTokenOK describes a response with status code 200, with default header values.

successful operation
*/
type GetCustomerTokenOK struct {
	Payload *models.ResponseContainerAPITokenModel
}

// IsSuccess returns true when this get customer token o k response has a 2xx status code
func (o *GetCustomerTokenOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customer token o k response has a 3xx status code
func (o *GetCustomerTokenOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customer token o k response has a 4xx status code
func (o *GetCustomerTokenOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customer token o k response has a 5xx status code
func (o *GetCustomerTokenOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customer token o k response a status code equal to that given
func (o *GetCustomerTokenOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetCustomerTokenOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/apitoken/customertokens/{id}][%d] getCustomerTokenOK  %+v", 200, o.Payload)
}

func (o *GetCustomerTokenOK) String() string {
	return fmt.Sprintf("[GET /api/v2/apitoken/customertokens/{id}][%d] getCustomerTokenOK  %+v", 200, o.Payload)
}

func (o *GetCustomerTokenOK) GetPayload() *models.ResponseContainerAPITokenModel {
	return o.Payload
}

func (o *GetCustomerTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerAPITokenModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
