// Code generated by go-swagger; DO NOT EDIT.

package api_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetCustomerTokensReader is a Reader for the GetCustomerTokens structure.
type GetCustomerTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCustomerTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCustomerTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCustomerTokensOK creates a GetCustomerTokensOK with default headers values
func NewGetCustomerTokensOK() *GetCustomerTokensOK {
	return &GetCustomerTokensOK{}
}

/*
GetCustomerTokensOK describes a response with status code 200, with default header values.

successful operation
*/
type GetCustomerTokensOK struct {
	Payload *models.ResponseContainerListAPITokenModel
}

// IsSuccess returns true when this get customer tokens o k response has a 2xx status code
func (o *GetCustomerTokensOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get customer tokens o k response has a 3xx status code
func (o *GetCustomerTokensOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get customer tokens o k response has a 4xx status code
func (o *GetCustomerTokensOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get customer tokens o k response has a 5xx status code
func (o *GetCustomerTokensOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get customer tokens o k response a status code equal to that given
func (o *GetCustomerTokensOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetCustomerTokensOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/apitoken/customertokens][%d] getCustomerTokensOK  %+v", 200, o.Payload)
}

func (o *GetCustomerTokensOK) String() string {
	return fmt.Sprintf("[GET /api/v2/apitoken/customertokens][%d] getCustomerTokensOK  %+v", 200, o.Payload)
}

func (o *GetCustomerTokensOK) GetPayload() *models.ResponseContainerListAPITokenModel {
	return o.Payload
}

func (o *GetCustomerTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerListAPITokenModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
