// Code generated by go-swagger; DO NOT EDIT.

package api_token

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewUpdateTokenNameServiceAccountParams creates a new UpdateTokenNameServiceAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateTokenNameServiceAccountParams() *UpdateTokenNameServiceAccountParams {
	return &UpdateTokenNameServiceAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateTokenNameServiceAccountParamsWithTimeout creates a new UpdateTokenNameServiceAccountParams object
// with the ability to set a timeout on a request.
func NewUpdateTokenNameServiceAccountParamsWithTimeout(timeout time.Duration) *UpdateTokenNameServiceAccountParams {
	return &UpdateTokenNameServiceAccountParams{
		timeout: timeout,
	}
}

// NewUpdateTokenNameServiceAccountParamsWithContext creates a new UpdateTokenNameServiceAccountParams object
// with the ability to set a context for a request.
func NewUpdateTokenNameServiceAccountParamsWithContext(ctx context.Context) *UpdateTokenNameServiceAccountParams {
	return &UpdateTokenNameServiceAccountParams{
		Context: ctx,
	}
}

// NewUpdateTokenNameServiceAccountParamsWithHTTPClient creates a new UpdateTokenNameServiceAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateTokenNameServiceAccountParamsWithHTTPClient(client *http.Client) *UpdateTokenNameServiceAccountParams {
	return &UpdateTokenNameServiceAccountParams{
		HTTPClient: client,
	}
}

/*
UpdateTokenNameServiceAccountParams contains all the parameters to send to the API endpoint

	for the update token name service account operation.

	Typically these are written to a http.Request.
*/
type UpdateTokenNameServiceAccountParams struct {

	/* Body.

	     Example Body:
	<pre>{
	  "tokenID": "Token identifier",
	  "tokenName": "Token name"
	}</pre>
	*/
	Body *models.UserAPIToken

	// ID.
	ID string

	// Token.
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update token name service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTokenNameServiceAccountParams) WithDefaults() *UpdateTokenNameServiceAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update token name service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateTokenNameServiceAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) WithTimeout(timeout time.Duration) *UpdateTokenNameServiceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) WithContext(ctx context.Context) *UpdateTokenNameServiceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) WithHTTPClient(client *http.Client) *UpdateTokenNameServiceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) WithBody(body *models.UserAPIToken) *UpdateTokenNameServiceAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) SetBody(body *models.UserAPIToken) {
	o.Body = body
}

// WithID adds the id to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) WithID(id string) *UpdateTokenNameServiceAccountParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) SetID(id string) {
	o.ID = id
}

// WithToken adds the token to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) WithToken(token string) *UpdateTokenNameServiceAccountParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the update token name service account params
func (o *UpdateTokenNameServiceAccountParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateTokenNameServiceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
