// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetAllWebhooksReader is a Reader for the GetAllWebhooks structure.
type GetAllWebhooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllWebhooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllWebhooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllWebhooksOK creates a GetAllWebhooksOK with default headers values
func NewGetAllWebhooksOK() *GetAllWebhooksOK {
	return &GetAllWebhooksOK{}
}

/*
GetAllWebhooksOK describes a response with status code 200, with default header values.

successful operation
*/
type GetAllWebhooksOK struct {
	Payload *models.ResponseContainerPagedNotificant
}

// IsSuccess returns true when this get all webhooks o k response has a 2xx status code
func (o *GetAllWebhooksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get all webhooks o k response has a 3xx status code
func (o *GetAllWebhooksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get all webhooks o k response has a 4xx status code
func (o *GetAllWebhooksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get all webhooks o k response has a 5xx status code
func (o *GetAllWebhooksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get all webhooks o k response a status code equal to that given
func (o *GetAllWebhooksOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetAllWebhooksOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/webhook][%d] getAllWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetAllWebhooksOK) String() string {
	return fmt.Sprintf("[GET /api/v2/webhook][%d] getAllWebhooksOK  %+v", 200, o.Payload)
}

func (o *GetAllWebhooksOK) GetPayload() *models.ResponseContainerPagedNotificant {
	return o.Payload
}

func (o *GetAllWebhooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerPagedNotificant)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
