// Code generated by go-swagger; DO NOT EDIT.

package derived_metric

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// GetDerivedMetricTagsReader is a Reader for the GetDerivedMetricTags structure.
type GetDerivedMetricTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDerivedMetricTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDerivedMetricTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDerivedMetricTagsOK creates a GetDerivedMetricTagsOK with default headers values
func NewGetDerivedMetricTagsOK() *GetDerivedMetricTagsOK {
	return &GetDerivedMetricTagsOK{}
}

/*
GetDerivedMetricTagsOK describes a response with status code 200, with default header values.

successful operation
*/
type GetDerivedMetricTagsOK struct {
	Payload *models.ResponseContainerTagsResponse
}

// IsSuccess returns true when this get derived metric tags o k response has a 2xx status code
func (o *GetDerivedMetricTagsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get derived metric tags o k response has a 3xx status code
func (o *GetDerivedMetricTagsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get derived metric tags o k response has a 4xx status code
func (o *GetDerivedMetricTagsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get derived metric tags o k response has a 5xx status code
func (o *GetDerivedMetricTagsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get derived metric tags o k response a status code equal to that given
func (o *GetDerivedMetricTagsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetDerivedMetricTagsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/derivedmetric/{id}/tag][%d] getDerivedMetricTagsOK  %+v", 200, o.Payload)
}

func (o *GetDerivedMetricTagsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/derivedmetric/{id}/tag][%d] getDerivedMetricTagsOK  %+v", 200, o.Payload)
}

func (o *GetDerivedMetricTagsOK) GetPayload() *models.ResponseContainerTagsResponse {
	return o.Payload
}

func (o *GetDerivedMetricTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerTagsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
