// Code generated by go-swagger; DO NOT EDIT.

package derived_metric

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDerivedMetricTagsParams creates a new GetDerivedMetricTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDerivedMetricTagsParams() *GetDerivedMetricTagsParams {
	return &GetDerivedMetricTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDerivedMetricTagsParamsWithTimeout creates a new GetDerivedMetricTagsParams object
// with the ability to set a timeout on a request.
func NewGetDerivedMetricTagsParamsWithTimeout(timeout time.Duration) *GetDerivedMetricTagsParams {
	return &GetDerivedMetricTagsParams{
		timeout: timeout,
	}
}

// NewGetDerivedMetricTagsParamsWithContext creates a new GetDerivedMetricTagsParams object
// with the ability to set a context for a request.
func NewGetDerivedMetricTagsParamsWithContext(ctx context.Context) *GetDerivedMetricTagsParams {
	return &GetDerivedMetricTagsParams{
		Context: ctx,
	}
}

// NewGetDerivedMetricTagsParamsWithHTTPClient creates a new GetDerivedMetricTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDerivedMetricTagsParamsWithHTTPClient(client *http.Client) *GetDerivedMetricTagsParams {
	return &GetDerivedMetricTagsParams{
		HTTPClient: client,
	}
}

/*
GetDerivedMetricTagsParams contains all the parameters to send to the API endpoint

	for the get derived metric tags operation.

	Typically these are written to a http.Request.
*/
type GetDerivedMetricTagsParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get derived metric tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDerivedMetricTagsParams) WithDefaults() *GetDerivedMetricTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get derived metric tags params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDerivedMetricTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) WithTimeout(timeout time.Duration) *GetDerivedMetricTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) WithContext(ctx context.Context) *GetDerivedMetricTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) WithHTTPClient(client *http.Client) *GetDerivedMetricTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) WithID(id string) *GetDerivedMetricTagsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get derived metric tags params
func (o *GetDerivedMetricTagsParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDerivedMetricTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
