// Code generated by go-swagger; DO NOT EDIT.

package derived_metric

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// UndeleteDerivedMetricReader is a Reader for the UndeleteDerivedMetric structure.
type UndeleteDerivedMetricReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UndeleteDerivedMetricReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUndeleteDerivedMetricOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUndeleteDerivedMetricOK creates a UndeleteDerivedMetricOK with default headers values
func NewUndeleteDerivedMetricOK() *UndeleteDerivedMetricOK {
	return &UndeleteDerivedMetricOK{}
}

/*
UndeleteDerivedMetricOK describes a response with status code 200, with default header values.

successful operation
*/
type UndeleteDerivedMetricOK struct {
	Payload *models.ResponseContainerDerivedMetricDefinition
}

// IsSuccess returns true when this undelete derived metric o k response has a 2xx status code
func (o *UndeleteDerivedMetricOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this undelete derived metric o k response has a 3xx status code
func (o *UndeleteDerivedMetricOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this undelete derived metric o k response has a 4xx status code
func (o *UndeleteDerivedMetricOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this undelete derived metric o k response has a 5xx status code
func (o *UndeleteDerivedMetricOK) IsServerError() bool {
	return false
}

// IsCode returns true when this undelete derived metric o k response a status code equal to that given
func (o *UndeleteDerivedMetricOK) IsCode(code int) bool {
	return code == 200
}

func (o *UndeleteDerivedMetricOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/derivedmetric/{id}/undelete][%d] undeleteDerivedMetricOK  %+v", 200, o.Payload)
}

func (o *UndeleteDerivedMetricOK) String() string {
	return fmt.Sprintf("[POST /api/v2/derivedmetric/{id}/undelete][%d] undeleteDerivedMetricOK  %+v", 200, o.Payload)
}

func (o *UndeleteDerivedMetricOK) GetPayload() *models.ResponseContainerDerivedMetricDefinition {
	return o.Payload
}

func (o *UndeleteDerivedMetricOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerDerivedMetricDefinition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
