// Code generated by go-swagger; DO NOT EDIT.

package metrics_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new metrics policy API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for metrics policy API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetMetricsPolicy(params *GetMetricsPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsPolicyOK, error)

	GetMetricsPolicyByVersion(params *GetMetricsPolicyByVersionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsPolicyByVersionOK, error)

	GetMetricsPolicyHistory(params *GetMetricsPolicyHistoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsPolicyHistoryOK, error)

	RevertMetricsPolicyByVersion(params *RevertMetricsPolicyByVersionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RevertMetricsPolicyByVersionOK, error)

	UpdateMetricsPolicy(params *UpdateMetricsPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateMetricsPolicyOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetMetricsPolicy gets the metrics policy
*/
func (a *Client) GetMetricsPolicy(params *GetMetricsPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMetricsPolicyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getMetricsPolicy",
		Method:             "GET",
		PathPattern:        "/api/v2/metricspolicy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMetricsPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMetricsPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMetricsPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMetricsPolicyByVersion gets a specific historical version of a metrics policy
*/
func (a *Client) GetMetricsPolicyByVersion(params *GetMetricsPolicyByVersionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsPolicyByVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMetricsPolicyByVersionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getMetricsPolicyByVersion",
		Method:             "GET",
		PathPattern:        "/api/v2/metricspolicy/history/{version}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMetricsPolicyByVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMetricsPolicyByVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMetricsPolicyByVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetMetricsPolicyHistory gets the version history of metrics policy
*/
func (a *Client) GetMetricsPolicyHistory(params *GetMetricsPolicyHistoryParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetMetricsPolicyHistoryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMetricsPolicyHistoryParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getMetricsPolicyHistory",
		Method:             "GET",
		PathPattern:        "/api/v2/metricspolicy/history",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetMetricsPolicyHistoryReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMetricsPolicyHistoryOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMetricsPolicyHistory: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
RevertMetricsPolicyByVersion reverts to a specific historical version of a metrics policy
*/
func (a *Client) RevertMetricsPolicyByVersion(params *RevertMetricsPolicyByVersionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RevertMetricsPolicyByVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRevertMetricsPolicyByVersionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "revertMetricsPolicyByVersion",
		Method:             "POST",
		PathPattern:        "/api/v2/metricspolicy/revert/{version}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &RevertMetricsPolicyByVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RevertMetricsPolicyByVersionOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for revertMetricsPolicyByVersion: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateMetricsPolicy updates the metrics policy
*/
func (a *Client) UpdateMetricsPolicy(params *UpdateMetricsPolicyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateMetricsPolicyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateMetricsPolicyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateMetricsPolicy",
		Method:             "PUT",
		PathPattern:        "/api/v2/metricspolicy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateMetricsPolicyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateMetricsPolicyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateMetricsPolicy: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
