// Code generated by go-swagger; DO NOT EDIT.

package metrics_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRevertMetricsPolicyByVersionParams creates a new RevertMetricsPolicyByVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRevertMetricsPolicyByVersionParams() *RevertMetricsPolicyByVersionParams {
	return &RevertMetricsPolicyByVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRevertMetricsPolicyByVersionParamsWithTimeout creates a new RevertMetricsPolicyByVersionParams object
// with the ability to set a timeout on a request.
func NewRevertMetricsPolicyByVersionParamsWithTimeout(timeout time.Duration) *RevertMetricsPolicyByVersionParams {
	return &RevertMetricsPolicyByVersionParams{
		timeout: timeout,
	}
}

// NewRevertMetricsPolicyByVersionParamsWithContext creates a new RevertMetricsPolicyByVersionParams object
// with the ability to set a context for a request.
func NewRevertMetricsPolicyByVersionParamsWithContext(ctx context.Context) *RevertMetricsPolicyByVersionParams {
	return &RevertMetricsPolicyByVersionParams{
		Context: ctx,
	}
}

// NewRevertMetricsPolicyByVersionParamsWithHTTPClient creates a new RevertMetricsPolicyByVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewRevertMetricsPolicyByVersionParamsWithHTTPClient(client *http.Client) *RevertMetricsPolicyByVersionParams {
	return &RevertMetricsPolicyByVersionParams{
		HTTPClient: client,
	}
}

/*
RevertMetricsPolicyByVersionParams contains all the parameters to send to the API endpoint

	for the revert metrics policy by version operation.

	Typically these are written to a http.Request.
*/
type RevertMetricsPolicyByVersionParams struct {

	// Version.
	//
	// Format: int64
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the revert metrics policy by version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RevertMetricsPolicyByVersionParams) WithDefaults() *RevertMetricsPolicyByVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the revert metrics policy by version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RevertMetricsPolicyByVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) WithTimeout(timeout time.Duration) *RevertMetricsPolicyByVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) WithContext(ctx context.Context) *RevertMetricsPolicyByVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) WithHTTPClient(client *http.Client) *RevertMetricsPolicyByVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithVersion adds the version to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) WithVersion(version int64) *RevertMetricsPolicyByVersionParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the revert metrics policy by version params
func (o *RevertMetricsPolicyByVersionParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *RevertMetricsPolicyByVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param version
	if err := r.SetPathParam("version", swag.FormatInt64(o.Version)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
