// Code generated by go-swagger; DO NOT EDIT.

package role

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"models"
)

// AddAssigneesReader is a Reader for the AddAssignees structure.
type AddAssigneesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddAssigneesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddAssigneesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddAssigneesOK creates a AddAssigneesOK with default headers values
func NewAddAssigneesOK() *AddAssigneesOK {
	return &AddAssigneesOK{}
}

/*
AddAssigneesOK describes a response with status code 200, with default header values.

successful operation
*/
type AddAssigneesOK struct {
	Payload *models.ResponseContainerRoleDTO
}

// IsSuccess returns true when this add assignees o k response has a 2xx status code
func (o *AddAssigneesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this add assignees o k response has a 3xx status code
func (o *AddAssigneesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this add assignees o k response has a 4xx status code
func (o *AddAssigneesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this add assignees o k response has a 5xx status code
func (o *AddAssigneesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this add assignees o k response a status code equal to that given
func (o *AddAssigneesOK) IsCode(code int) bool {
	return code == 200
}

func (o *AddAssigneesOK) Error() string {
	return fmt.Sprintf("[POST /api/v2/role/{id}/addAssignees][%d] addAssigneesOK  %+v", 200, o.Payload)
}

func (o *AddAssigneesOK) String() string {
	return fmt.Sprintf("[POST /api/v2/role/{id}/addAssignees][%d] addAssigneesOK  %+v", 200, o.Payload)
}

func (o *AddAssigneesOK) GetPayload() *models.ResponseContainerRoleDTO {
	return o.Payload
}

func (o *AddAssigneesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseContainerRoleDTO)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
