// Code generated by go-swagger; DO NOT EDIT.

package monitored_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"models"
)

// NewUpdateService2Params creates a new UpdateService2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateService2Params() *UpdateService2Params {
	return &UpdateService2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateService2ParamsWithTimeout creates a new UpdateService2Params object
// with the ability to set a timeout on a request.
func NewUpdateService2ParamsWithTimeout(timeout time.Duration) *UpdateService2Params {
	return &UpdateService2Params{
		timeout: timeout,
	}
}

// NewUpdateService2ParamsWithContext creates a new UpdateService2Params object
// with the ability to set a context for a request.
func NewUpdateService2ParamsWithContext(ctx context.Context) *UpdateService2Params {
	return &UpdateService2Params{
		Context: ctx,
	}
}

// NewUpdateService2ParamsWithHTTPClient creates a new UpdateService2Params object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateService2ParamsWithHTTPClient(client *http.Client) *UpdateService2Params {
	return &UpdateService2Params{
		HTTPClient: client,
	}
}

/*
UpdateService2Params contains all the parameters to send to the API endpoint

	for the update service 2 operation.

	Typically these are written to a http.Request.
*/
type UpdateService2Params struct {

	// Application.
	Application string

	/* Body.

	     Example Body:
	<pre>{
	  "satisfiedLatencyMillis": "100000",
	  "customDashboardLink": "shopping-dashboard",
	  "hidden": "false"
	}</pre>
	*/
	Body *models.MonitoredServiceDTO

	// Service.
	Service string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update service 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateService2Params) WithDefaults() *UpdateService2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update service 2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateService2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update service 2 params
func (o *UpdateService2Params) WithTimeout(timeout time.Duration) *UpdateService2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update service 2 params
func (o *UpdateService2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update service 2 params
func (o *UpdateService2Params) WithContext(ctx context.Context) *UpdateService2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update service 2 params
func (o *UpdateService2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update service 2 params
func (o *UpdateService2Params) WithHTTPClient(client *http.Client) *UpdateService2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update service 2 params
func (o *UpdateService2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplication adds the application to the update service 2 params
func (o *UpdateService2Params) WithApplication(application string) *UpdateService2Params {
	o.SetApplication(application)
	return o
}

// SetApplication adds the application to the update service 2 params
func (o *UpdateService2Params) SetApplication(application string) {
	o.Application = application
}

// WithBody adds the body to the update service 2 params
func (o *UpdateService2Params) WithBody(body *models.MonitoredServiceDTO) *UpdateService2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update service 2 params
func (o *UpdateService2Params) SetBody(body *models.MonitoredServiceDTO) {
	o.Body = body
}

// WithService adds the service to the update service 2 params
func (o *UpdateService2Params) WithService(service string) *UpdateService2Params {
	o.SetService(service)
	return o
}

// SetService adds the service to the update service 2 params
func (o *UpdateService2Params) SetService(service string) {
	o.Service = service
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateService2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application
	if err := r.SetPathParam("application", o.Application); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param service
	if err := r.SetPathParam("service", o.Service); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
